import { VARIANT_DEFAULT_STOCK_INVENTORY_FIELD_SUFFIXES } from "./product-query-config"

export const CATEGORY_FIELDS =
  "id,name,handle,parent_category_id,rank,is_active,category_children"

export const CATALOG_DEFAULT_LIMIT = 24
export const CATALOG_DEFAULT_SORT = "recommended"
export const ORDER_DEFAULT_SORT = "-created_at"

const CART_ITEM_VARIANT_INVENTORY_FIELDS = [
  "items.variant.id",
  "+items.variant.inventory_quantity",
  "+items.variant.manage_inventory",
  "+items.variant.allow_backorder",
  ...VARIANT_DEFAULT_STOCK_INVENTORY_FIELD_SUFFIXES.map(
    (field) => `items.variant.${field}`,
  ),
]

export const CART_FIELDS = [
  "id",
  "region_id",
  "customer_id",
  "sales_channel_id",
  "email",
  "currency_code",
  "metadata",
  "created_at",
  "updated_at",
  "original_item_total",
  "original_item_subtotal",
  "original_item_tax_total",
  "item_total",
  "item_subtotal",
  "item_tax_total",
  "original_total",
  "original_subtotal",
  "original_tax_total",
  "total",
  "subtotal",
  "tax_total",
  "discount_total",
  "discount_tax_total",
  "gift_card_total",
  "gift_card_tax_total",
  "shipping_total",
  "shipping_subtotal",
  "shipping_tax_total",
  "original_shipping_total",
  "original_shipping_subtotal",
  "original_shipping_tax_total",
  "completed_at",
  "billing_address.*",
  "shipping_address.*",
  "region.*",
  "promotions.*",
  "payment_collection.*",
  "payment_collection.payment_sessions.*",
  "*items",
  ...CART_ITEM_VARIANT_INVENTORY_FIELDS,
  "items.tax_lines.*",
  "items.adjustments.*",
  "shipping_methods.*",
  "shipping_methods.tax_lines.*",
  "shipping_methods.adjustments.*",
].join(",")

export const ORDER_LIST_FIELDS = [
  "id",
  "display_id",
  "status",
  "payment_status",
  "fulfillment_status",
  "created_at",
  "updated_at",
  "currency_code",
  "total",
  "item_total",
  "items.id",
  "items.quantity",
].join(",")

export const ORDER_DETAIL_FIELDS = [
  "id",
  "display_id",
  "status",
  "payment_status",
  "fulfillment_status",
  "created_at",
  "updated_at",
  "currency_code",
  "email",
  "total",
  "subtotal",
  "original_total",
  "original_subtotal",
  "original_tax_total",
  "item_total",
  "item_subtotal",
  "item_tax_total",
  "shipping_total",
  "shipping_subtotal",
  "shipping_tax_total",
  "tax_total",
  "discount_total",
  "discount_tax_total",
  "gift_card_total",
  "gift_card_tax_total",
  "billing_address.*",
  "shipping_address.*",
  "shipping_methods.*",
  "shipping_methods.tax_lines.*",
  "transactions.*",
  "payment_collections.*",
  "*items",
  "items.tax_lines.*",
].join(",")
