minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@techsio/storybook-better-a11y'
  - '@techsio/storybook-a11y-reporter'
  - '@medusajs/*'
  - '@paykit-sdk/*'
  - '@rokmohar/medusa-plugin-meilisearch'
# trustPolicy: no-downgrade

packages:
  - packages/**
  - apps/**
  - libs/**
  - '!apps/demo/**'
  - '!apps/e2e/**'
  - '!apps/typesense-demo/**'

syncInjectedDepsAfterScripts:
  - build

ignoredBuiltDependencies:
  - '@medusajs/telemetry'
  - core-js
  - msgpackr-extract
  - protobufjs
  - puppeteer

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - nx
  - sharp
  - unrs-resolver
