minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@techsio/storybook-better-a11y'
  - '@techsio/storybook-a11y-reporter'
  - '@medusajs/*'
  - '@paykit-sdk/*'
  - '@rokmohar/medusa-plugin-meilisearch'
# trustPolicy: no-downgrade

strictPeerDependencies: true
disallowWorkspaceCycles: true
dedupeDirectDeps: true
injectWorkspacePackages: true
verifyDepsBeforeRun: false
storeDir: .pnpm-store
publicHoistPattern:
  - eslint
  - eslint-*
  - '@eslint/*'
  - '@typescript-eslint/*'
  - typescript
  - tailwindcss
  - tailwind-*
  - '@tailwindcss/*'
  - postcss
  - postcss-*
  - '@iconify/tailwind4'
  - vite
  - vitest
  - '@vitejs/*'
  - storybook
  - storybook-*
  - '@storybook/*'
  - '@rsbuild/*'
  - '@medusajs/*'

overrides:
  csstype: 3.1.3
  react: 19.2.3
  react-dom: 19.2.3
  '@types/react': 19.2.3
  '@types/react-dom': 19.2.3
  '@types/node': 24.12.4
  '@medusajs/admin-bundler>vite': 8.1.3
  '@medusajs/admin-vite-plugin>vite': 8.1.3
  '@medusajs/admin-bundler>@vitejs/plugin-react': 6.0.3
  vite: 8.1.3

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl

# Manual dependency metadata extensions for packages with incomplete published metadata.
packageExtensions:
  '@payloadcms/ui@3.85.1':
    dependencies:
      '@floating-ui/react': 0.27.19
  '@pigment/auto-translate@1.3.4':
    dependencies:
      '@payloadcms/ui': 3.85.1
  '@medusajs/caching@2.16.0':
    dependencies:
      graphql: 16.14.0
  '@medusajs/core-flows@2.16.0':
    dependencies:
      '@medusajs/utils': 2.16.0
      '@medusajs/workflows-sdk': 2.16.0
  '@rokmohar/medusa-plugin-meilisearch@*':
    dependencies:
      '@medusajs/js-sdk': ^2.16.0

patchedDependencies:
  medusa-plugin-content@0.2.0: patches/medusa-plugin-content@0.2.0.patch
  '@lexical/code@0.35.0': patches/@lexical__code@0.35.0.patch
  object-inspect@1.13.4: patches/object-inspect@1.13.4.patch

packages:
  - packages/**
  - apps/**
  - libs/**
  - '!apps/demo/**'
  - '!apps/e2e/**'
  - '!apps/typesense-demo/**'

syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  '@nubjs/nub': true
  '@biomejs/biome': true
  '@medusajs/telemetry': false
  '@parcel/watcher': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  core-js: false
  es5-ext: false
  esbuild: true
  msgpackr-extract: false
  msw: false
  nx: true
  protobufjs: false
  puppeteer: false
  sharp: true
  unrs-resolver: true
