import type { StorefrontTextDefinition } from "../registry"

export const STOREFRONT_ACCOUNT_ORDERS_TEXT_DEFINITIONS = [
  {
    description: "Nadpis při přesměrování nepřihlášeného zákazníka.",
    key: "auth.account.redirect.title",
    namespace: "auth",
    values: {
      cz: "Přesměrování na přihlášení",
      hu: "Átirányítás a bejelentkezéshez",
      ro: "Redirecționare către autentificare",
      sk: "Presmerovanie na prihlásenie",
    },
  },
  {
    description: "Vysvětlení přístupu k účtu pouze po přihlášení.",
    key: "auth.account.redirect.description",
    namespace: "auth",
    values: {
      cz: "Účet je dostupný pouze přihlášeným uživatelům.",
      hu: "A fiók csak bejelentkezett felhasználók számára érhető el.",
      ro: "Contul este disponibil doar utilizatorilor autentificați.",
      sk: "Účet je dostupný iba pre prihlásených používateľov.",
    },
  },
  {
    description: "Navigační položka přehledu zákaznického účtu.",
    key: "auth.account.navigation.overview",
    namespace: "auth",
    values: {
      cz: "Přehled",
      hu: "Áttekintés",
      ro: "Prezentare generală",
      sk: "Prehľad",
    },
  },
  {
    description: "Navigační položka objednávek zákazníka.",
    key: "auth.account.navigation.orders",
    namespace: "auth",
    values: {
      cz: "Objednávky",
      hu: "Rendelések",
      ro: "Comenzi",
      sk: "Objednávky",
    },
  },
  {
    description: "Navigační položka produktových seznamů zákazníka.",
    key: "auth.account.navigation.lists",
    namespace: "auth",
    values: {
      cz: "Seznamy",
      hu: "Listák",
      ro: "Liste",
      sk: "Zoznamy",
    },
  },
  {
    description: "Navigační položka nastavení zákaznického účtu.",
    key: "auth.account.navigation.settings",
    namespace: "auth",
    values: {
      cz: "Nastavení",
      hu: "Beállítások",
      ro: "Setări",
      sk: "Nastavenia",
    },
  },
  {
    description: "Akce pro odhlášení zákazníka.",
    key: "auth.account.logout",
    namespace: "auth",
    values: {
      cz: "Odhlásit se",
      hu: "Kijelentkezés",
      ro: "Deconectare",
      sk: "Odhlásiť sa",
    },
  },
  {
    description: "Záložní chyba při neúspěšném odhlášení.",
    key: "auth.account.logout_failed",
    namespace: "auth",
    values: {
      cz: "Odhlášení se nezdařilo. Zkuste to znovu.",
      hu: "Nem sikerült kijelentkezni. Próbálja újra.",
      ro: "Deconectarea nu a reușit. Încercați din nou.",
      sk: "Odhlásenie zlyhalo. Skúste to znova.",
    },
  },
  {
    description: "Nadpis přehledu zákaznického účtu.",
    key: "auth.account.overview.title",
    namespace: "auth",
    values: {
      cz: "Přehled účtu",
      hu: "A fiók áttekintése",
      ro: "Prezentarea generală a contului",
      sk: "Prehľad účtu",
    },
  },
  {
    description: "Popis přehledu zákaznického účtu.",
    key: "auth.account.overview.description",
    namespace: "auth",
    values: {
      cz: "Správa objednávek a údajů zákazníka.",
      hu: "Rendelések és ügyféladatok kezelése.",
      ro: "Gestionarea comenzilor și a datelor clientului.",
      sk: "Správa objednávok a údajov zákazníka.",
    },
  },
  {
    description: "Popisek zákazníka v přehledu účtu.",
    key: "auth.account.overview.customer",
    namespace: "auth",
    values: {
      cz: "Zákazník",
      hu: "Vásárló",
      ro: "Client",
      sk: "Zákazník",
    },
  },
  {
    description: "Záložní označení zákazníka bez jména.",
    key: "auth.account.overview.customer_fallback",
    namespace: "auth",
    values: {
      cz: "Zákazník",
      hu: "Vásárló",
      ro: "Client",
      sk: "Zákazník",
    },
  },
  {
    description: "Nadpis nastavení zákaznického účtu.",
    key: "auth.account.settings.title",
    namespace: "auth",
    values: {
      cz: "Nastavení účtu",
      hu: "Fiókbeállítások",
      ro: "Setările contului",
      sk: "Nastavenia účtu",
    },
  },
  {
    description: "Zpráva při nedostupných údajích zákaznického účtu.",
    key: "auth.account.settings.unavailable",
    namespace: "auth",
    values: {
      cz: "Údaje účtu nejsou dostupné. Zkuste stránku obnovit.",
      hu: "A fiók adatai nem érhetők el. Frissítse az oldalt.",
      ro: "Datele contului nu sunt disponibile. Reîmprospătați pagina.",
      sk: "Údaje účtu nie sú dostupné. Skúste stránku obnoviť.",
    },
  },
  {
    description: "Popis formuláře nastavení zákaznického účtu.",
    key: "auth.account.settings.description",
    namespace: "auth",
    values: {
      cz: "Aktualizujte osobní údaje pro rychlejší dokončení objednávky.",
      hu: "Frissítse személyes adatait a gyorsabb fizetéshez.",
      ro: "Actualizați datele personale pentru finalizarea mai rapidă a comenzii.",
      sk: "Aktualizujte osobné údaje pre rýchlejší checkout.",
    },
  },
  {
    description: "Potvrzení uložení nastavení zákaznického účtu.",
    key: "auth.account.settings.saved",
    namespace: "auth",
    values: {
      cz: "Údaje účtu byly uloženy.",
      hu: "A fiók adatai mentve.",
      ro: "Datele contului au fost salvate.",
      sk: "Údaje účtu boli uložené.",
    },
  },
  {
    description: "Akce pro uložení nastavení zákaznického účtu.",
    key: "auth.account.settings.save",
    namespace: "auth",
    values: {
      cz: "Uložit údaje",
      hu: "Adatok mentése",
      ro: "Salvează datele",
      sk: "Uložiť údaje",
    },
  },
  {
    description: "Popisek pole e-mailu, které nelze upravit.",
    key: "auth.account.settings.email_read_only",
    namespace: "auth",
    values: {
      cz: "{label} (nelze upravit)",
      hu: "{label} (nem módosítható)",
      ro: "{label} (nu poate fi modificat)",
      sk: "{label} (nemožno upraviť)",
    },
  },
  {
    description: "Popisek volitelného pole firmy.",
    key: "auth.account.settings.company_optional",
    namespace: "auth",
    values: {
      cz: "{label} (volitelné)",
      hu: "{label} (opcionális)",
      ro: "{label} (opțional)",
      sk: "{label} (voliteľné)",
    },
  },
  {
    description: "Záložní chyba při ukládání nastavení účtu.",
    key: "auth.account.settings.update_failed",
    namespace: "auth",
    values: {
      cz: "Údaje účtu se nepodařilo uložit. Zkuste to znovu.",
      hu: "Nem sikerült menteni a fiók adatait. Próbálja újra.",
      ro: "Datele contului nu au putut fi salvate. Încercați din nou.",
      sk: "Údaje účtu sa nepodarilo uložiť. Skúste to znova.",
    },
  },
  {
    description: "Akce pro opakované načtení objednávek.",
    key: "auth.account.orders.retry",
    namespace: "auth",
    values: {
      cz: "Zkusit znovu",
      hu: "Újrapróbálkozás",
      ro: "Încearcă din nou",
      sk: "Skúsiť znova",
    },
  },
  {
    description: "Popis prázdné historie objednávek.",
    key: "auth.account.orders.empty_description",
    namespace: "auth",
    values: {
      cz: "Zatím nemáte žádnou dokončenou objednávku.",
      hu: "Még nincs befejezett rendelése.",
      ro: "Nu aveți încă nicio comandă finalizată.",
      sk: "Zatiaľ nemáte žiadnu dokončenú objednávku.",
    },
  },
  {
    description: "Akce z prázdné historie objednávek do katalogu.",
    key: "auth.account.orders.browse_products",
    namespace: "auth",
    values: {
      cz: "Přejít na produkty",
      hu: "Tovább a termékekhez",
      ro: "Mergi la produse",
      sk: "Prejsť na produkty",
    },
  },
  {
    description: "Popis historie objednávek.",
    key: "auth.account.orders.description",
    namespace: "auth",
    values: {
      cz: "Přehled dokončených objednávek s položkami a stavem doručení.",
      hu: "A befejezett rendelések áttekintése tételekkel és szállítási állapottal.",
      ro: "Prezentarea comenzilor finalizate, cu articole și starea livrării.",
      sk: "Prehľad dokončených objednávok s položkami a stavom doručenia.",
    },
  },
  {
    description: "Souhrn počtu objednávek a aktuální stránky.",
    key: "auth.account.orders.pagination_summary",
    namespace: "auth",
    values: {
      cz: "Celkem: {count} | Strana {currentPage}/{totalPages}",
      hu: "Összesen: {count} | {currentPage}/{totalPages}. oldal",
      ro: "Total: {count} | Pagina {currentPage}/{totalPages}",
      sk: "Celkom: {count} | Strana {currentPage}/{totalPages}",
    },
  },
  {
    description: "Akce pro návrat do historie objednávek.",
    key: "auth.account.orders.back",
    namespace: "auth",
    values: {
      cz: "Zpět na objednávky",
      hu: "Vissza a rendelésekhez",
      ro: "Înapoi la comenzi",
      sk: "Späť na objednávky",
    },
  },
  {
    description: "Nadpis nenalezeného detailu objednávky.",
    key: "auth.account.orders.not_found_title",
    namespace: "auth",
    values: {
      cz: "Objednávka nebyla nalezena",
      hu: "A rendelés nem található",
      ro: "Comanda nu a fost găsită",
      sk: "Objednávka nebola nájdená",
    },
  },
  {
    description: "Popis nenalezeného detailu objednávky.",
    key: "auth.account.orders.not_found_description",
    namespace: "auth",
    values: {
      cz: "Zkontrolujte URL nebo se vraťte do seznamu objednávek.",
      hu: "Ellenőrizze az URL-címet, vagy térjen vissza a rendelések listájához.",
      ro: "Verificați adresa URL sau reveniți la lista comenzilor.",
      sk: "Skontrolujte URL alebo sa vráťte do zoznamu objednávok.",
    },
  },
  {
    description: "Počet položek v objednávce.",
    key: "auth.account.orders.item_count",
    namespace: "auth",
    values: {
      cz: "{count, plural, one {# položka v objednávce} few {# položky v objednávce} other {# položek v objednávce}}",
      hu: "{count, plural, other {# tétel a rendelésben}}",
      ro: "{count, plural, one {# articol în comandă} few {# articole în comandă} other {# de articole în comandă}}",
      sk: "{count, plural, one {# položka v objednávke} few {# položky v objednávke} other {# položiek v objednávke}}",
    },
  },
  {
    description: "Popisek celkové částky objednávky.",
    key: "auth.account.orders.total_amount",
    namespace: "auth",
    values: {
      cz: "Celková částka",
      hu: "Végösszeg",
      ro: "Suma totală",
      sk: "Celková suma",
    },
  },
  {
    description: "Akce pro zobrazení faktury objednávky.",
    key: "auth.account.orders.view_invoice",
    namespace: "auth",
    values: {
      cz: "Zobrazit fakturu",
      hu: "Számla megtekintése",
      ro: "Vezi factura",
      sk: "Zobraziť faktúru",
    },
  },
  {
    description: "Akce pro zobrazení detailu objednávky.",
    key: "auth.account.orders.view_order",
    namespace: "auth",
    values: {
      cz: "Zobrazit objednávku",
      hu: "Rendelés megtekintése",
      ro: "Vezi comanda",
      sk: "Zobraziť objednávku",
    },
  },
  {
    description: "Popisek produktu v položkách objednávky.",
    key: "auth.account.orders.product",
    namespace: "auth",
    values: {
      cz: "Produkt",
      hu: "Termék",
      ro: "Produs",
      sk: "Produkt",
    },
  },
  {
    description: "Popisek ceny v položkách objednávky.",
    key: "auth.account.orders.price",
    namespace: "auth",
    values: {
      cz: "Cena",
      hu: "Ár",
      ro: "Preț",
      sk: "Cena",
    },
  },
  {
    description: "Popisek informačního sloupce v položkách objednávky.",
    key: "auth.account.orders.info",
    namespace: "auth",
    values: {
      cz: "Informace",
      hu: "Információ",
      ro: "Informații",
      sk: "Info",
    },
  },
  {
    description: "Záložní název produktu v objednávce.",
    key: "auth.account.orders.product_fallback",
    namespace: "auth",
    values: {
      cz: "Produkt",
      hu: "Termék",
      ro: "Produs",
      sk: "Produkt",
    },
  },
  {
    description: "Popisek množství položky objednávky s hodnotou.",
    key: "auth.account.orders.quantity_value",
    namespace: "auth",
    values: {
      cz: "Množství: {count}",
      hu: "Mennyiség: {count}",
      ro: "Cantitate: {count}",
      sk: "Množstvo: {count}",
    },
  },
  {
    description: "Akce pro zobrazení detailu produktu z objednávky.",
    key: "auth.account.orders.product_detail",
    namespace: "auth",
    values: {
      cz: "Detail",
      hu: "Részletek",
      ro: "Detalii",
      sk: "Detail",
    },
  },
  {
    description: "Zpráva pro objednávku bez položek.",
    key: "auth.account.orders.no_items",
    namespace: "auth",
    values: {
      cz: "Objednávka neobsahuje žádné položky.",
      hu: "A rendelés nem tartalmaz tételeket.",
      ro: "Comanda nu conține articole.",
      sk: "Objednávka neobsahuje položky.",
    },
  },
  {
    description: "Nadpis detailu objednávky s číslem objednávky.",
    key: "auth.account.orders.detail.order_title",
    namespace: "auth",
    values: {
      cz: "Objednávka {orderId}",
      hu: "Rendelés {orderId}",
      ro: "Comanda {orderId}",
      sk: "Objednávka {orderId}",
    },
  },
  {
    description: "Datum vytvoření objednávky.",
    key: "auth.account.orders.detail.created",
    namespace: "auth",
    values: {
      cz: "Vytvořeno: {date}",
      hu: "Létrehozva: {date}",
      ro: "Creată: {date}",
      sk: "Vytvorená: {date}",
    },
  },
  {
    description: "Krátký label faktury objednávky.",
    key: "auth.account.orders.invoice",
    namespace: "auth",
    values: {
      cz: "Faktura",
      hu: "Számla",
      ro: "Factură",
      sk: "Faktúra",
    },
  },
  {
    description: "Nadpis cenového souhrnu objednávky.",
    key: "auth.account.orders.detail.payment_summary",
    namespace: "auth",
    values: {
      cz: "Souhrn platby",
      hu: "Fizetési összesítő",
      ro: "Sumarul plății",
      sk: "Zhrnutie platby",
    },
  },
  {
    description: "Nadpis technických detailů objednávky.",
    key: "auth.account.orders.detail.order_details",
    namespace: "auth",
    values: {
      cz: "Detaily objednávky",
      hu: "Rendelés részletei",
      ro: "Detaliile comenzii",
      sk: "Detaily objednávky",
    },
  },
  {
    description: "Identifikátor objednávky v technických detailech.",
    key: "auth.account.orders.detail.order_id",
    namespace: "auth",
    values: {
      cz: "ID: {id}",
      hu: "Azonosító: {id}",
      ro: "ID: {id}",
      sk: "ID: {id}",
    },
  },
  {
    description: "Popisek počtu položek v technických detailech.",
    key: "auth.account.orders.detail.items",
    namespace: "auth",
    values: {
      cz: "Položky: {count}",
      hu: "Tételek: {count}",
      ro: "Articole: {count}",
      sk: "Položky: {count}",
    },
  },
  {
    description: "Datum poslední aktualizace objednávky.",
    key: "auth.account.orders.detail.updated",
    namespace: "auth",
    values: {
      cz: "Aktualizováno: {date}",
      hu: "Frissítve: {date}",
      ro: "Actualizată: {date}",
      sk: "Aktualizované: {date}",
    },
  },
  {
    description: "Nadpis doručovací adresy objednávky.",
    key: "auth.account.orders.detail.shipping_address",
    namespace: "auth",
    values: {
      cz: "Doručovací adresa",
      hu: "Szállítási cím",
      ro: "Adresa de livrare",
      sk: "Doručovacia adresa",
    },
  },
  {
    description: "Nadpis fakturační adresy objednávky.",
    key: "auth.account.orders.detail.billing_address",
    namespace: "auth",
    values: {
      cz: "Fakturační adresa",
      hu: "Számlázási cím",
      ro: "Adresa de facturare",
      sk: "Fakturačná adresa",
    },
  },
  {
    description: "Zpráva při chybějící adrese objednávky.",
    key: "auth.account.orders.detail.address_unavailable",
    namespace: "auth",
    values: {
      cz: "Adresa není dostupná.",
      hu: "A cím nem érhető el.",
      ro: "Adresa nu este disponibilă.",
      sk: "Adresa nie je dostupná.",
    },
  },
  {
    description: "Nadpis dopravy v detailu objednávky.",
    key: "auth.account.orders.detail.shipping",
    namespace: "auth",
    values: {
      cz: "Doprava",
      hu: "Szállítás",
      ro: "Livrare",
      sk: "Doprava",
    },
  },
  {
    description: "Zpráva při chybějícím způsobu dopravy.",
    key: "auth.account.orders.detail.shipping_unavailable",
    namespace: "auth",
    values: {
      cz: "Způsob dopravy není dostupný",
      hu: "A szállítási mód nem érhető el",
      ro: "Metoda de livrare nu este disponibilă",
      sk: "Spôsob dopravy nie je dostupný",
    },
  },
  {
    description: "Nadpis platby v detailu objednávky.",
    key: "auth.account.orders.detail.payment",
    namespace: "auth",
    values: {
      cz: "Platba",
      hu: "Fizetés",
      ro: "Plată",
      sk: "Platba",
    },
  },
  {
    description: "Zpráva při chybějícím způsobu platby.",
    key: "auth.account.orders.detail.payment_unavailable",
    namespace: "auth",
    values: {
      cz: "Způsob platby není dostupný",
      hu: "A fizetési mód nem érhető el",
      ro: "Metoda de plată nu este disponibilă",
      sk: "Spôsob platby nie je dostupný",
    },
  },
  {
    description: "Nadpis sledování zásilky v detailu objednávky.",
    key: "auth.account.orders.detail.tracking",
    namespace: "auth",
    values: {
      cz: "Sledování zásilky",
      hu: "Csomagkövetés",
      ro: "Urmărire",
      sk: "Tracking",
    },
  },
  {
    description: "Zpráva při chybějícím kódu pro sledování zásilky.",
    key: "auth.account.orders.detail.tracking_unavailable",
    namespace: "auth",
    values: {
      cz: "Kód pro sledování zásilky není dostupný",
      hu: "A csomagkövetési kód nem érhető el",
      ro: "Codul de urmărire nu este disponibil",
      sk: "Tracking kód nie je dostupný",
    },
  },
  {
    description: "Popisek stavu dopravy nebo platby.",
    key: "auth.account.orders.detail.status",
    namespace: "auth",
    values: {
      cz: "Stav: {status}",
      hu: "Állapot: {status}",
      ro: "Stare: {status}",
      sk: "Stav: {status}",
    },
  },
  {
    description: "Nadpis seznamu položek objednávky.",
    key: "auth.account.orders.detail.items_title",
    namespace: "auth",
    values: {
      cz: "Položky objednávky",
      hu: "A rendelés tételei",
      ro: "Articolele comenzii",
      sk: "Položky objednávky",
    },
  },
  {
    description: "Popisek varianty položky objednávky.",
    key: "auth.account.orders.variant",
    namespace: "auth",
    values: {
      cz: "Varianta",
      hu: "Változat",
      ro: "Variantă",
      sk: "Varianta",
    },
  },
  {
    description: "Popisek množství položky objednávky.",
    key: "auth.account.orders.quantity",
    namespace: "auth",
    values: {
      cz: "Množství",
      hu: "Mennyiség",
      ro: "Cantitate",
      sk: "Množstvo",
    },
  },
  {
    description: "Popisek jednotkové ceny položky objednávky.",
    key: "auth.account.orders.unit_price",
    namespace: "auth",
    values: {
      cz: "Cena za kus",
      hu: "Egységár",
      ro: "Preț unitar",
      sk: "Cena za kus",
    },
  },
  {
    description: "Popisek celkové ceny položky objednávky.",
    key: "auth.account.orders.total",
    namespace: "auth",
    values: {
      cz: "Celkem",
      hu: "Összesen",
      ro: "Total",
      sk: "Celkom",
    },
  },
  {
    description: "Jednotková cena položky objednávky s hodnotou.",
    key: "auth.account.orders.unit_price_value",
    namespace: "auth",
    values: {
      cz: "Cena/ks: {amount}",
      hu: "Egységár: {amount}",
      ro: "Preț unitar: {amount}",
      sk: "Cena/ks: {amount}",
    },
  },
  {
    description: "Lokalizovaný stav životního cyklu objednávky.",
    key: "auth.account.orders.status.lifecycle",
    namespace: "auth",
    values: {
      cz: "{status, select, archived {Uzavřená} canceled {Zrušená} completed {Dokončená} draft {Rozpracovaná} pending {Zpracovává se} requires_action {Vyžaduje akci} other {{status}}}",
      hu: "{status, select, archived {Lezárt} canceled {Törölve} completed {Teljesítve} draft {Piszkozat} pending {Feldolgozás alatt} requires_action {Beavatkozást igényel} other {{status}}}",
      ro: "{status, select, archived {Arhivată} canceled {Anulată} completed {Finalizată} draft {Ciornă} pending {În procesare} requires_action {Necesită acțiune} other {{status}}}",
      sk: "{status, select, archived {Uzavretá} canceled {Zrušená} completed {Dokončená} draft {Rozpracovaná} pending {Spracováva sa} requires_action {Vyžaduje akciu} other {{status}}}",
    },
  },
  {
    description: "Lokalizovaný stav platby objednávky.",
    key: "auth.account.orders.status.payment",
    namespace: "auth",
    values: {
      cz: "{status, select, authorized {Platba ověřena} awaiting {Čeká na platbu} canceled {Platba zrušena} captured {Zaplaceno} not_paid {Čeká na platbu} partially_authorized {Částečně ověřena} partially_captured {Částečně zaplaceno} partially_refunded {Částečně vráceno} refunded {Vráceno} requires_action {Platba vyžaduje akci} other {{status}}}",
      hu: "{status, select, authorized {Fizetés engedélyezve} awaiting {Fizetésre vár} canceled {Fizetés törölve} captured {Fizetve} not_paid {Fizetésre vár} partially_authorized {Részben engedélyezve} partially_captured {Részben kifizetve} partially_refunded {Részben visszatérítve} refunded {Visszatérítve} requires_action {A fizetés beavatkozást igényel} other {{status}}}",
      ro: "{status, select, authorized {Plată autorizată} awaiting {În așteptarea plății} canceled {Plată anulată} captured {Plătită} not_paid {În așteptarea plății} partially_authorized {Autorizată parțial} partially_captured {Plătită parțial} partially_refunded {Rambursată parțial} refunded {Rambursată} requires_action {Plata necesită acțiune} other {{status}}}",
      sk: "{status, select, authorized {Platba overená} awaiting {Čaká na platbu} canceled {Platba zrušená} captured {Zaplatená} not_paid {Čaká na platbu} partially_authorized {Čiastočne overená} partially_captured {Čiastočne zaplatená} partially_refunded {Čiastočne vrátená} refunded {Vrátená} requires_action {Platba vyžaduje akciu} other {{status}}}",
    },
  },
  {
    description: "Lokalizovaný stav doručení objednávky.",
    key: "auth.account.orders.status.fulfillment",
    namespace: "auth",
    values: {
      cz: "{status, select, canceled {Doručení zrušeno} delivered {Doručena} fulfilled {Připravena k odeslání} not_fulfilled {Zpracovává se} partially_delivered {Částečně doručena} partially_fulfilled {Částečně připravena} partially_shipped {Částečně odeslána} shipped {Odeslána} other {{status}}}",
      hu: "{status, select, canceled {Szállítás törölve} delivered {Kézbesítve} fulfilled {Feladásra kész} not_fulfilled {Feldolgozás alatt} partially_delivered {Részben kézbesítve} partially_fulfilled {Részben előkészítve} partially_shipped {Részben feladva} shipped {Feladva} other {{status}}}",
      ro: "{status, select, canceled {Livrare anulată} delivered {Livrată} fulfilled {Pregătită pentru expediere} not_fulfilled {În procesare} partially_delivered {Livrată parțial} partially_fulfilled {Pregătită parțial} partially_shipped {Expediată parțial} shipped {Expediată} other {{status}}}",
      sk: "{status, select, canceled {Doručenie zrušené} delivered {Doručená} fulfilled {Pripravená na odoslanie} not_fulfilled {Spracováva sa} partially_delivered {Čiastočne doručená} partially_fulfilled {Čiastočne pripravená} partially_shipped {Čiastočne odoslaná} shipped {Odoslaná} other {{status}}}",
    },
  },
] as const satisfies readonly StorefrontTextDefinition[]
