import type { StorefrontTextDefinition } from "../registry"

export const STOREFRONT_CATALOG_TEXT_DEFINITIONS = [
  {
    description: "Název odkazu na přehled značek.",
    key: "catalog.brands.label",
    namespace: "catalog",
    values: {
      cz: "Značky",
      hu: "Márkák",
      ro: "Mărci",
      sk: "Značky",
    },
  },
  {
    description: "Nadpis abecedního přehledu všech značek.",
    key: "catalog.brands.all_title",
    namespace: "catalog",
    values: {
      cz: "Všechny značky A-Z",
      hu: "Összes márka A-tól Z-ig",
      ro: "Toate mărcile de la A la Z",
      sk: "Všetky značky A-Z",
    },
  },
  {
    description: "Přístupný název abecedního seznamu značek.",
    key: "catalog.brands.list_aria",
    namespace: "catalog",
    values: {
      cz: "Seznam značek podle abecedy",
      hu: "Márkák betűrend szerinti listája",
      ro: "Lista mărcilor în ordine alfabetică",
      sk: "Zoznam značiek podľa abecedy",
    },
  },
  {
    description: "Label ovládání katalogových filtrů s počtem aktivních filtrů.",
    key: "catalog.filters.toggle",
    namespace: "catalog",
    values: {
      cz: "{count, plural, =0 {Filtr} other {Filtr (#)}}",
      hu: "{count, plural, =0 {Szűrő} other {Szűrő (#)}}",
      ro: "{count, plural, =0 {Filtre} other {Filtre (#)}}",
      sk: "{count, plural, =0 {Filter} other {Filter (#)}}",
    },
  },
  {
    description: "Nadpis filtru ceny.",
    key: "catalog.filters.price",
    namespace: "catalog",
    values: {
      cz: "Cena",
      hu: "Ár",
      ro: "Preț",
      sk: "Cena",
    },
  },
  {
    description: "Nadpis filtru formy produktu.",
    key: "catalog.filters.form",
    namespace: "catalog",
    values: {
      cz: "Forma",
      hu: "Forma",
      ro: "Formă",
      sk: "Forma",
    },
  },
  {
    description: "Nadpis filtru značky.",
    key: "catalog.filters.brand",
    namespace: "catalog",
    values: {
      cz: "Značka",
      hu: "Márka",
      ro: "Marcă",
      sk: "Značka",
    },
  },
  {
    description: "Nadpis filtru účinné látky.",
    key: "catalog.filters.active_ingredient",
    namespace: "catalog",
    values: {
      cz: "Účinná látka",
      hu: "Hatóanyag",
      ro: "Ingredient activ",
      sk: "Aktívna látka",
    },
  },
  {
    description: "Akce pro vymazání všech katalogových filtrů.",
    key: "catalog.filters.clear",
    namespace: "catalog",
    values: {
      cz: "Vymazat filtry",
      hu: "Szűrők törlése",
      ro: "Șterge filtrele",
      sk: "Vymazať filtre",
    },
  },
  {
    description: "Akce pro rozbalení dalších hodnot filtru.",
    key: "catalog.filters.show_more",
    namespace: "catalog",
    values: {
      cz: "Zobrazit více",
      hu: "Több megjelenítése",
      ro: "Afișează mai multe",
      sk: "Zobraziť viac",
    },
  },
  {
    description: "Akce pro sbalení dalších hodnot filtru.",
    key: "catalog.filters.show_less",
    namespace: "catalog",
    values: {
      cz: "Zobrazit méně",
      hu: "Kevesebb megjelenítése",
      ro: "Afișează mai puține",
      sk: "Zobraziť menej",
    },
  },
  {
    description: "Prázdný stav při načítání forem produktu.",
    key: "catalog.filters.form_loading",
    namespace: "catalog",
    values: {
      cz: "Formy se načítají.",
      hu: "A formák betöltése folyamatban van.",
      ro: "Formele se încarcă.",
      sk: "Formy sa načítavajú.",
    },
  },
  {
    description: "Prázdný stav filtru forem produktu.",
    key: "catalog.filters.form_empty",
    namespace: "catalog",
    values: {
      cz: "Formy zatím nejsou dostupné.",
      hu: "A formák egyelőre nem érhetők el.",
      ro: "Formele nu sunt disponibile momentan.",
      sk: "Formy zatiaľ nie sú dostupné.",
    },
  },
  {
    description: "Prázdný stav při načítání značek.",
    key: "catalog.filters.brand_loading",
    namespace: "catalog",
    values: {
      cz: "Značky se načítají.",
      hu: "A márkák betöltése folyamatban van.",
      ro: "Mărcile se încarcă.",
      sk: "Značky sa načítavajú.",
    },
  },
  {
    description: "Prázdný stav filtru značek.",
    key: "catalog.filters.brand_empty",
    namespace: "catalog",
    values: {
      cz: "Značky zatím nejsou dostupné.",
      hu: "A márkák egyelőre nem érhetők el.",
      ro: "Mărcile nu sunt disponibile momentan.",
      sk: "Značky zatiaľ nie sú dostupné.",
    },
  },
  {
    description: "Prázdný stav při načítání účinných látek.",
    key: "catalog.filters.ingredient_loading",
    namespace: "catalog",
    values: {
      cz: "Účinné látky se načítají.",
      hu: "A hatóanyagok betöltése folyamatban van.",
      ro: "Ingredientele active se încarcă.",
      sk: "Aktívne látky sa načítavajú.",
    },
  },
  {
    description: "Prázdný stav filtru účinných látek.",
    key: "catalog.filters.ingredient_empty",
    namespace: "catalog",
    values: {
      cz: "Účinné látky zatím nejsou dostupné.",
      hu: "A hatóanyagok egyelőre nem érhetők el.",
      ro: "Ingredientele active nu sunt disponibile momentan.",
      sk: "Aktívne látky zatiaľ nie sú dostupné.",
    },
  },
  {
    description: "Label filtru produktů skladem.",
    key: "catalog.filters.status.in_stock",
    namespace: "catalog",
    values: {
      cz: "Skladem",
      hu: "Raktáron",
      ro: "În stoc",
      sk: "Na sklade",
    },
  },
  {
    description: "Label filtru akčních produktů.",
    key: "catalog.filters.status.action",
    namespace: "catalog",
    values: {
      cz: "Akce",
      hu: "Akció",
      ro: "Promoție",
      sk: "Akcia",
    },
  },
  {
    description: "Label filtru nových produktů.",
    key: "catalog.filters.status.new",
    namespace: "catalog",
    values: {
      cz: "Novinka",
      hu: "Újdonság",
      ro: "Noutate",
      sk: "Novinka",
    },
  },
  {
    description: "Label filtru doporučených produktů.",
    key: "catalog.filters.status.tip",
    namespace: "catalog",
    values: {
      cz: "Tip",
      hu: "Tipp",
      ro: "Recomandare",
      sk: "Tip",
    },
  },
  {
    description: "Label filtru veganských produktů.",
    key: "catalog.filters.status.vegan",
    namespace: "catalog",
    values: {
      cz: "Vegan",
      hu: "Vegán",
      ro: "Vegan",
      sk: "Vegan",
    },
  },
  {
    description: "Label filtru produktů ve formě kapslí.",
    key: "catalog.filters.form_values.capsules",
    namespace: "catalog",
    values: {
      cz: "Kapsle",
      hu: "Kapszula",
      ro: "Capsule",
      sk: "Kapsuly",
    },
  },
  {
    description: "Label filtru produktů ve formě tablet.",
    key: "catalog.filters.form_values.tablets",
    namespace: "catalog",
    values: {
      cz: "Tablety",
      hu: "Tabletta",
      ro: "Tablete",
      sk: "Tablety",
    },
  },
  {
    description: "Label filtru produktů ve formě měkkých kapslí.",
    key: "catalog.filters.form_values.softgel",
    namespace: "catalog",
    values: {
      cz: "Softgel",
      hu: "Lágy kapszula",
      ro: "Capsule moi",
      sk: "Softgel",
    },
  },
  {
    description: "Label filtru produktů v prášku.",
    key: "catalog.filters.form_values.powder",
    namespace: "catalog",
    values: {
      cz: "Prášek",
      hu: "Por",
      ro: "Pulbere",
      sk: "Prášok",
    },
  },
  {
    description: "Label filtru tekutých produktů.",
    key: "catalog.filters.form_values.liquid",
    namespace: "catalog",
    values: {
      cz: "Tekutiny",
      hu: "Folyadékok",
      ro: "Lichide",
      sk: "Tekutiny",
    },
  },
  {
    description: "Label filtru produktů ve formě nápoje.",
    key: "catalog.filters.form_values.drink",
    namespace: "catalog",
    values: {
      cz: "Nápoj",
      hu: "Ital",
      ro: "Băutură",
      sk: "Nápoj",
    },
  },
  {
    description: "Label filtru produktů ve formě kapek.",
    key: "catalog.filters.form_values.drops",
    namespace: "catalog",
    values: {
      cz: "Kapky",
      hu: "Cseppek",
      ro: "Picături",
      sk: "Kvapky",
    },
  },
  {
    description: "Label filtru produktů ve spreji.",
    key: "catalog.filters.form_values.spray",
    namespace: "catalog",
    values: {
      cz: "Sprej",
      hu: "Spray",
      ro: "Spray",
      sk: "Sprej",
    },
  },
  {
    description: "Label filtru produktů ve formě sirupu.",
    key: "catalog.filters.form_values.syrup",
    namespace: "catalog",
    values: {
      cz: "Sirup",
      hu: "Szirup",
      ro: "Sirop",
      sk: "Sirup",
    },
  },
  {
    description: "Přístupný název stránkování katalogu.",
    key: "catalog.pagination.root_aria",
    namespace: "catalog",
    values: {
      cz: "Stránkování produktů",
      hu: "Termékek lapozása",
      ro: "Paginarea produselor",
      sk: "Stránkovanie produktov",
    },
  },
  {
    description: "Přístupný label navigace na předchozí stránku katalogu.",
    key: "catalog.pagination.previous_aria",
    namespace: "catalog",
    values: {
      cz: "Předchozí stránka",
      hu: "Előző oldal",
      ro: "Pagina anterioară",
      sk: "Predchádzajúca strana",
    },
  },
  {
    description: "Přístupný label navigace na další stránku katalogu.",
    key: "catalog.pagination.next_aria",
    namespace: "catalog",
    values: {
      cz: "Další stránka",
      hu: "Következő oldal",
      ro: "Pagina următoare",
      sk: "Nasledujúca strana",
    },
  },
  {
    description: "Přístupný label konkrétní stránky katalogu.",
    key: "catalog.pagination.page_aria",
    namespace: "catalog",
    values: {
      cz: "Stránka {page} z {totalPages}",
      hu: "{page}. oldal, összesen {totalPages}",
      ro: "Pagina {page} din {totalPages}",
      sk: "Strana {page} z {totalPages}",
    },
  },
  {
    description: "Popisek řazení produktů podle doporučení.",
    key: "catalog.sort.recommended",
    namespace: "catalog",
    values: {
      cz: "Doporučujeme",
      hu: "Ajánlott",
      ro: "Recomandate",
      sk: "Odporúčame",
    },
  },
  {
    description: "Popisek řazení produktů od nejlevnějších.",
    key: "catalog.sort.price_asc",
    namespace: "catalog",
    values: {
      cz: "Nejlevnější",
      hu: "Legolcsóbb",
      ro: "Cele mai ieftine",
      sk: "Najlacnejšie",
    },
  },
  {
    description: "Popisek řazení produktů od nejdražších.",
    key: "catalog.sort.price_desc",
    namespace: "catalog",
    values: {
      cz: "Nejdražší",
      hu: "Legdrágább",
      ro: "Cele mai scumpe",
      sk: "Najdrahšie",
    },
  },
  {
    description: "Popisek řazení produktů podle prodejnosti.",
    key: "catalog.sort.best_selling",
    namespace: "catalog",
    values: {
      cz: "Nejprodávanější",
      hu: "Legkelendőbb",
      ro: "Cele mai vândute",
      sk: "Najpredávanejšie",
    },
  },
  {
    description: "Popisek řazení produktů od nejnovějších.",
    key: "catalog.sort.newest",
    namespace: "catalog",
    values: {
      cz: "Nejnovější",
      hu: "Legújabb",
      ro: "Cele mai noi",
      sk: "Najnovšie",
    },
  },
  {
    description: "Popisek celkového počtu produktů ve výpisu.",
    key: "catalog.results.items_total",
    namespace: "catalog",
    values: {
      cz: "položek celkem",
      hu: "összesen",
      ro: "articole în total",
      sk: "položiek celkom",
    },
  },
  {
    description: "Prázdný stav kategorie pro zvolený filtr.",
    key: "catalog.results.empty_category",
    namespace: "catalog",
    values: {
      cz: "V této kategorii zatím nejsou dostupné produkty pro zvolený filtr.",
      hu: "Ebben a kategóriában jelenleg nincsenek elérhető termékek a kiválasztott szűrőhöz.",
      ro: "În această categorie nu sunt disponibile momentan produse pentru filtrul selectat.",
      sk: "V tejto kategórii zatiaľ nie sú dostupné produkty pre zvolený filter.",
    },
  },
  {
    description: "Prázdný stav značky pro zvolený filtr.",
    key: "catalog.results.empty_brand",
    namespace: "catalog",
    values: {
      cz: "Tato značka zatím nemá dostupné produkty pro zvolený filtr.",
      hu: "Ehhez a márkához jelenleg nincsenek elérhető termékek a kiválasztott szűrőhöz.",
      ro: "Pentru această marcă nu sunt disponibile momentan produse pentru filtrul selectat.",
      sk: "Táto značka zatiaľ nemá dostupné produkty pre zvolený filter.",
    },
  },
  {
    description: "Chybová hláška pro nenalezenou kategorii.",
    key: "catalog.results.category_not_found",
    namespace: "catalog",
    values: {
      cz: "Kategorii se nepodařilo najít. Zkontrolujte URL nebo vyberte jinou kategorii.",
      hu: "A kategória nem található. Ellenőrizze az URL-t, vagy válasszon másik kategóriát.",
      ro: "Categoria nu a putut fi găsită. Verificați adresa URL sau selectați o altă categorie.",
      sk: "Kategóriu sa nepodarilo nájsť. Skontrolujte URL alebo vyberte inú kategóriu.",
    },
  },
  {
    description: "Chybová hláška při načítání produktů.",
    key: "catalog.errors.products_load_failed",
    namespace: "catalog",
    values: {
      cz: "Načtení produktů selhalo.",
      hu: "A termékek betöltése sikertelen.",
      ro: "Încărcarea produselor a eșuat.",
      sk: "Načítanie produktov zlyhalo.",
    },
  },
  {
    description: "Chybová hláška při načítání kategorií.",
    key: "catalog.errors.categories_load_failed",
    namespace: "catalog",
    values: {
      cz: "Načtení kategorií selhalo.",
      hu: "A kategóriák betöltése sikertelen.",
      ro: "Încărcarea categoriilor a eșuat.",
      sk: "Načítanie kategórií zlyhalo.",
    },
  },
] as const satisfies readonly StorefrontTextDefinition[]
