import type { StorefrontTextDefinition } from "../registry"

export const STOREFRONT_PRODUCT_LIST_TEXT_DEFINITIONS = [
  {
    description: "Nadpis zákaznických seznamů produktů.",
    key: "auth.product_lists.title",
    namespace: "auth",
    values: {
      cz: "Seznamy produktů",
      hu: "Terméklisták",
      ro: "Liste de produse",
      sk: "Zoznamy produktov",
    },
  },
  {
    description: "Popis zákaznických seznamů produktů.",
    key: "auth.product_lists.description",
    namespace: "auth",
    values: {
      cz: "Uložené produkty a vlastní nákupní seznamy.",
      hu: "Mentett termékek és saját bevásárlólisták.",
      ro: "Produse salvate și liste de cumpărături proprii.",
      sk: "Uložené produkty a vlastné nákupné zoznamy.",
    },
  },
  {
    description: "Prázdný stav zákaznických seznamů produktů.",
    key: "auth.product_lists.empty_description",
    namespace: "auth",
    values: {
      cz: "Zatím nemáte žádný seznam produktů.",
      hu: "Még nincs terméklistája.",
      ro: "Nu aveți încă nicio listă de produse.",
      sk: "Zatiaľ nemáte žiadny zoznam produktov.",
    },
  },
  {
    description: "Akce pro vytvoření nového seznamu produktů.",
    key: "auth.product_lists.new_list",
    namespace: "auth",
    values: {
      cz: "Nový seznam",
      hu: "Új lista",
      ro: "Listă nouă",
      sk: "Nový zoznam",
    },
  },
  {
    description: "Akce pro přechod z prázdného seznamu do katalogu.",
    key: "auth.product_lists.browse_products",
    namespace: "auth",
    values: {
      cz: "Přejít na produkty",
      hu: "Termékek megtekintése",
      ro: "Vezi produsele",
      sk: "Prejsť na produkty",
    },
  },
  {
    description: "Akce pro opakování načtení seznamů produktů.",
    key: "auth.product_lists.retry",
    namespace: "auth",
    values: {
      cz: "Zkusit znovu",
      hu: "Újrapróbálás",
      ro: "Încearcă din nou",
      sk: "Skúsiť znova",
    },
  },
  {
    description: "Chyba při načítání zákaznických seznamů produktů.",
    key: "auth.product_lists.errors.lists_load_failed",
    namespace: "auth",
    values: {
      cz: "Seznamy se nepodařilo načíst.",
      hu: "A listákat nem sikerült betölteni.",
      ro: "Listele nu au putut fi încărcate.",
      sk: "Zoznamy sa nepodarilo načítať.",
    },
  },
  {
    description: "Chyba při načítání jednoho seznamu produktů.",
    key: "auth.product_lists.errors.list_load_failed",
    namespace: "auth",
    values: {
      cz: "Seznam se nepodařilo načíst.",
      hu: "A listát nem sikerült betölteni.",
      ro: "Lista nu a putut fi încărcată.",
      sk: "Zoznam sa nepodarilo načítať.",
    },
  },
  {
    description: "Prázdný stav vybraného seznamu produktů.",
    key: "auth.product_lists.list_empty",
    namespace: "auth",
    values: {
      cz: "Tento seznam je zatím prázdný.",
      hu: "Ez a lista még üres.",
      ro: "Această listă este momentan goală.",
      sk: "Tento zoznam je zatiaľ prázdny.",
    },
  },
  {
    description: "Přístupný stav načítání produktů vybraného seznamu.",
    key: "auth.product_lists.loading_items_aria",
    namespace: "auth",
    values: {
      cz: "Načítám produkty seznamu",
      hu: "A lista termékeinek betöltése",
      ro: "Se încarcă produsele din listă",
      sk: "Načítavam produkty zoznamu",
    },
  },
  {
    description: "Nadpis dialogu pro vytvoření seznamu produktů.",
    key: "auth.product_lists.create_dialog_title",
    namespace: "auth",
    values: {
      cz: "Jak se má seznam jmenovat?",
      hu: "Mi legyen a lista neve?",
      ro: "Cum se va numi lista?",
      sk: "Ako sa má zoznam volať?",
    },
  },
  {
    description: "Popisek pole pro název nového seznamu.",
    key: "auth.product_lists.new_list_name",
    namespace: "auth",
    values: {
      cz: "Název nového seznamu",
      hu: "Az új lista neve",
      ro: "Numele listei noi",
      sk: "Názov nového zoznamu",
    },
  },
  {
    description: "Placeholder pole pro název seznamu.",
    key: "auth.product_lists.new_list_placeholder",
    namespace: "auth",
    values: {
      cz: "Název seznamu",
      hu: "Lista neve",
      ro: "Numele listei",
      sk: "Názov zoznamu",
    },
  },
  {
    description: "Akce pro zrušení dialogu seznamu produktů.",
    key: "auth.product_lists.actions.cancel",
    namespace: "auth",
    values: {
      cz: "Zrušit",
      hu: "Mégse",
      ro: "Anulează",
      sk: "Zrušiť",
    },
  },
  {
    description: "Akce pro uložení seznamu produktů.",
    key: "auth.product_lists.actions.save",
    namespace: "auth",
    values: {
      cz: "Uložit",
      hu: "Mentés",
      ro: "Salvează",
      sk: "Uložiť",
    },
  },
  {
    description: "Akce pro potvrzení v pickeru seznamů.",
    key: "auth.product_lists.actions.confirm",
    namespace: "auth",
    values: {
      cz: "OK",
      hu: "OK",
      ro: "OK",
      sk: "OK",
    },
  },
  {
    description: "Akce pro smazání seznamu produktů.",
    key: "auth.product_lists.actions.delete_list",
    namespace: "auth",
    values: {
      cz: "Smazat seznam",
      hu: "Lista törlése",
      ro: "Șterge lista",
      sk: "Zmazať zoznam",
    },
  },
  {
    description: "Popis následků smazání seznamu produktů.",
    key: "auth.product_lists.delete_description",
    namespace: "auth",
    values: {
      cz: "Seznam bude odstraněn včetně uložených položek.",
      hu: "A lista a mentett tételekkel együtt törlődik.",
      ro: "Lista va fi ștearsă împreună cu articolele salvate.",
      sk: "Zoznam bude odstránený vrátane uložených položiek.",
    },
  },
  {
    description: "Nadpis potvrzení smazání pojmenovaného seznamu.",
    key: "auth.product_lists.delete_title",
    namespace: "auth",
    values: {
      cz: "Smazat seznam {listTitle}?",
      hu: "Törli a(z) {listTitle} listát?",
      ro: "Ștergi lista {listTitle}?",
      sk: "Zmazať zoznam {listTitle}?",
    },
  },
  {
    description: "Přístupný popisek smazání pojmenovaného seznamu.",
    key: "auth.product_lists.delete_list_aria",
    namespace: "auth",
    values: {
      cz: "Smazat seznam {listTitle}",
      hu: "A(z) {listTitle} lista törlése",
      ro: "Șterge lista {listTitle}",
      sk: "Zmazať zoznam {listTitle}",
    },
  },
  {
    description: "Přístupný popisek vytvoření nového seznamu.",
    key: "auth.product_lists.create_list_aria",
    namespace: "auth",
    values: {
      cz: "Vytvořit nový seznam",
      hu: "Új lista létrehozása",
      ro: "Creează o listă nouă",
      sk: "Vytvoriť nový zoznam",
    },
  },
  {
    description: "Výchozí název seznamu oblíbených produktů.",
    key: "auth.product_lists.favorite_title",
    namespace: "auth",
    values: {
      cz: "Oblíbené",
      hu: "Kedvencek",
      ro: "Favorite",
      sk: "Obľúbené",
    },
  },
  {
    description: "Výchozí název nepojmenovaného seznamu produktů.",
    key: "auth.product_lists.untitled_list",
    namespace: "auth",
    values: {
      cz: "Seznam",
      hu: "Lista",
      ro: "Listă",
      sk: "Zoznam",
    },
  },
  {
    description: "Nadpis pickeru seznamů produktů.",
    key: "auth.product_lists.picker.title",
    namespace: "auth",
    values: {
      cz: "Vyberte seznam",
      hu: "Válasszon listát",
      ro: "Selectează lista",
      sk: "Vyberte zoznam",
    },
  },
  {
    description: "Přístupný popisek otevření pickeru seznamů.",
    key: "auth.product_lists.picker.trigger_aria",
    namespace: "auth",
    values: {
      cz: "Přidat do seznamu",
      hu: "Hozzáadás listához",
      ro: "Adaugă într-o listă",
      sk: "Pridať do zoznamu",
    },
  },
  {
    description: "Výzva k přihlášení před uložením produktu do seznamu.",
    key: "auth.product_lists.picker.auth_required",
    namespace: "auth",
    values: {
      cz: "Pro ukládání produktů do seznamů se prosím přihlaste.",
      hu: "A termékek listákba mentéséhez jelentkezzen be.",
      ro: "Autentificați-vă pentru a salva produse în liste.",
      sk: "Na ukladanie produktov do zoznamov sa prosím prihláste.",
    },
  },
  {
    description: "Přístupný stav produktu již uloženého v seznamu.",
    key: "auth.product_lists.picker.contains_product_aria",
    namespace: "auth",
    values: {
      cz: "Seznam {listTitle} již obsahuje produkt",
      hu: "A(z) {listTitle} lista már tartalmazza a terméket",
      ro: "Lista {listTitle} conține deja produsul",
      sk: "Zoznam {listTitle} už obsahuje produkt",
    },
  },
  {
    description: "Přístupná akce přidání produktu do pojmenovaného seznamu.",
    key: "auth.product_lists.picker.add_to_list_aria",
    namespace: "auth",
    values: {
      cz: "Přidat do seznamu {listTitle}",
      hu: "Hozzáadás a(z) {listTitle} listához",
      ro: "Adaugă în lista {listTitle}",
      sk: "Pridať do zoznamu {listTitle}",
    },
  },
  {
    description: "Přístupná akce otevření pojmenovaného seznamu.",
    key: "auth.product_lists.picker.open_list_aria",
    namespace: "auth",
    values: {
      cz: "Otevřít seznam {listTitle}",
      hu: "A(z) {listTitle} lista megnyitása",
      ro: "Deschide lista {listTitle}",
      sk: "Otvoriť zoznam {listTitle}",
    },
  },
  {
    description: "Přístupný stav přidávání produktu do seznamu.",
    key: "auth.product_lists.picker.adding_product",
    namespace: "auth",
    values: {
      cz: "Přidávám produkt",
      hu: "Termék hozzáadása",
      ro: "Se adaugă produsul",
      sk: "Pridávam produkt",
    },
  },
  {
    description: "Formát množství položky seznamu.",
    key: "auth.product_lists.item.quantity",
    namespace: "auth",
    values: {
      cz: "{quantity} ks",
      hu: "{quantity} db",
      ro: "{quantity} buc.",
      sk: "{quantity} ks",
    },
  },
  {
    description: "Přístupný popisek pole množství položky seznamu.",
    key: "auth.product_lists.item.quantity_aria",
    namespace: "auth",
    values: {
      cz: "Množství pro {productName}",
      hu: "Mennyiség ehhez: {productName}",
      ro: "Cantitate pentru {productName}",
      sk: "Množstvo pre {productName}",
    },
  },
  {
    description: "Přístupná akce odstranění produktu ze seznamu.",
    key: "auth.product_lists.item.remove_aria",
    namespace: "auth",
    values: {
      cz: "Odstranit {productName} ze seznamu",
      hu: "A(z) {productName} eltávolítása a listáról",
      ro: "Elimină {productName} din listă",
      sk: "Odstrániť {productName} zo zoznamu",
    },
  },
  {
    description: "Stav odstraňování produktu ze seznamu.",
    key: "auth.product_lists.item.removing",
    namespace: "auth",
    values: {
      cz: "Odstraňuji",
      hu: "Eltávolítás",
      ro: "Se elimină",
      sk: "Odstraňujem",
    },
  },
  {
    description: "Stav produktu, který již není dostupný.",
    key: "auth.product_lists.availability.product_unavailable",
    namespace: "auth",
    values: {
      cz: "Produkt není dostupný",
      hu: "A termék nem elérhető",
      ro: "Produsul nu este disponibil",
      sk: "Produkt nie je dostupný",
    },
  },
  {
    description: "Stav produktu, který momentálně není skladem.",
    key: "auth.product_lists.availability.out_of_stock",
    namespace: "auth",
    values: {
      cz: "Momentálně není skladem",
      hu: "Jelenleg nincs készleten",
      ro: "Momentan nu este în stoc",
      sk: "Momentálne nie je skladom",
    },
  },
  {
    description: "Stav produktu s omezeným dostupným množstvím.",
    key: "auth.product_lists.availability.limited_stock",
    namespace: "auth",
    values: {
      cz: "Dostupné pouze {quantity} ks",
      hu: "Csak {quantity} db érhető el",
      ro: "Doar {quantity} buc. disponibile",
      sk: "Dostupné len {quantity} ks",
    },
  },
  {
    description: "Tlačítko seznamu bez položek dostupných ke koupi.",
    key: "auth.product_lists.availability.none_available",
    namespace: "auth",
    values: {
      cz: "Žádné dostupné položky",
      hu: "Nincs elérhető tétel",
      ro: "Niciun articol disponibil",
      sk: "Žiadne dostupné položky",
    },
  },
  {
    description: "Akce přidání všech položek seznamu do košíku.",
    key: "auth.product_lists.availability.add_all",
    namespace: "auth",
    values: {
      cz: "Přidat vše do košíku",
      hu: "Összes hozzáadása a kosárhoz",
      ro: "Adaugă totul în coș",
      sk: "Pridať všetko do košíka",
    },
  },
  {
    description: "Akce přidání dostupných položek seznamu do košíku.",
    key: "auth.product_lists.availability.add_available",
    namespace: "auth",
    values: {
      cz: "Přidat dostupné do košíku",
      hu: "Elérhetők hozzáadása a kosárhoz",
      ro: "Adaugă articolele disponibile în coș",
      sk: "Pridať dostupné do košíka",
    },
  },
  {
    description: "Zástupný text nedostupné ceny položek seznamu.",
    key: "auth.product_lists.price_unavailable",
    namespace: "auth",
    values: {
      cz: "Není dostupné",
      hu: "Nem érhető el",
      ro: "Indisponibil",
      sk: "Nie je dostupné",
    },
  },
  {
    description: "Validace prázdného názvu seznamu.",
    key: "auth.product_lists.validation.title_required",
    namespace: "auth",
    values: {
      cz: "Zadejte název seznamu.",
      hu: "Adja meg a lista nevét.",
      ro: "Introduceți numele listei.",
      sk: "Zadajte názov zoznamu.",
    },
  },
  {
    description: "Chyba při vytvoření seznamu produktů.",
    key: "auth.product_lists.errors.create_failed",
    namespace: "auth",
    values: {
      cz: "Seznam se nepodařilo vytvořit.",
      hu: "A listát nem sikerült létrehozni.",
      ro: "Lista nu a putut fi creată.",
      sk: "Zoznam sa nepodarilo vytvoriť.",
    },
  },
  {
    description: "Chyba při přidání produktu do seznamu.",
    key: "auth.product_lists.errors.add_product_failed",
    namespace: "auth",
    values: {
      cz: "Produkt se nepodařilo přidat.",
      hu: "A terméket nem sikerült hozzáadni.",
      ro: "Produsul nu a putut fi adăugat.",
      sk: "Produkt sa nepodarilo pridať.",
    },
  },
  {
    description: "Chyba při přidání celého seznamu do košíku.",
    key: "auth.product_lists.errors.add_list_to_cart_failed",
    namespace: "auth",
    values: {
      cz: "Seznam se nepodařilo přidat do košíku.",
      hu: "A listát nem sikerült a kosárhoz adni.",
      ro: "Lista nu a putut fi adăugată în coș.",
      sk: "Zoznam sa nepodarilo pridať do košíka.",
    },
  },
  {
    description: "Chyba seznamu obsahujícího produkt bez zvolené varianty.",
    key: "auth.product_lists.errors.missing_variant",
    namespace: "auth",
    values: {
      cz: "Některé produkty v seznamu nemají vybranou variantu.",
      hu: "A lista egyes termékeinél nincs kiválasztva változat.",
      ro: "Unele produse din listă nu au o variantă selectată.",
      sk: "Niektoré produkty v zozname nemajú vybranú variantu.",
    },
  },
  {
    description: "Chyba při nepovedeném přidání všech dostupných položek.",
    key: "auth.product_lists.errors.add_available_all_failed",
    namespace: "auth",
    values: {
      cz: "Dostupné položky se nepodařilo přidat do košíku.",
      hu: "Az elérhető tételeket nem sikerült a kosárhoz adni.",
      ro: "Articolele disponibile nu au putut fi adăugate în coș.",
      sk: "Dostupné položky sa nepodarilo pridať do košíka.",
    },
  },
  {
    description: "Upozornění při nepovedeném přidání části dostupných položek.",
    key: "auth.product_lists.errors.add_available_partial_failed",
    namespace: "auth",
    values: {
      cz: "Některé dostupné položky se nepodařilo přidat do košíku.",
      hu: "Néhány elérhető tételt nem sikerült a kosárhoz adni.",
      ro: "Unele articole disponibile nu au putut fi adăugate în coș.",
      sk: "Niektoré dostupné položky sa nepodarilo pridať do košíka.",
    },
  },
  {
    description: "Chyba při změně množství položky seznamu.",
    key: "auth.product_lists.errors.quantity_update_failed",
    namespace: "auth",
    values: {
      cz: "Množství se nepodařilo upravit.",
      hu: "A mennyiséget nem sikerült módosítani.",
      ro: "Cantitatea nu a putut fi actualizată.",
      sk: "Množstvo sa nepodarilo upraviť.",
    },
  },
  {
    description: "Chyba při smazání seznamu produktů.",
    key: "auth.product_lists.errors.delete_list_failed",
    namespace: "auth",
    values: {
      cz: "Seznam se nepodařilo smazat.",
      hu: "A listát nem sikerült törölni.",
      ro: "Lista nu a putut fi ștearsă.",
      sk: "Zoznam sa nepodarilo zmazať.",
    },
  },
  {
    description: "Chyba při odstranění produktu ze seznamu.",
    key: "auth.product_lists.errors.remove_product_failed",
    namespace: "auth",
    values: {
      cz: "Produkt se nepodařilo odstranit ze seznamu.",
      hu: "A terméket nem sikerült eltávolítani a listáról.",
      ro: "Produsul nu a putut fi eliminat din listă.",
      sk: "Produkt sa nepodarilo odstrániť zo zoznamu.",
    },
  },
] as const satisfies readonly StorefrontTextDefinition[]
