-- Immutable migration: the checksum-verified migration runner owns BEGIN/COMMIT.
-- IDs are generated by the command boundary so this schema needs no extension.
-- Security boundary: the migrator owner is separate from runtime identities.
-- The only supported runtime write path is the URLR command adapter; human and
-- read roles receive no direct DML grants.
-- This migration does not itself revoke owner DML or prove arbitrary owner DML is audited.
-- Before enablement, the deployment gate must verify separate credentials and
-- grants plus adapter-level atomicity and rollback. A SECURITY DEFINER procedure
-- boundary, if required, is a separate hardening decision before S8.

CREATE SCHEMA IF NOT EXISTS url_registry;

CREATE TABLE url_registry.url_route (
  id uuid PRIMARY KEY,
  market text NOT NULL CHECK (market IN ('sk', 'cz', 'hu', 'ro')),
  kind text NOT NULL CHECK (
    length(kind) BETWEEN 1 AND 64
    AND kind = btrim(kind)
  ),
  target_type text NOT NULL CHECK (target_type IN ('entity', 'static')),
  source_system text,
  source_type text,
  source_id text,
  static_route_key text,
  equivalence_key text,
  index_policy text NOT NULL CHECK (index_policy IN ('indexable', 'noindex')),
  status text NOT NULL CHECK (status IN ('active', 'retired', 'superseded')),
  successor_route_id uuid,
  successor_required_status text GENERATED ALWAYS AS (
    CASE
      WHEN successor_route_id IS NULL THEN NULL
      ELSE 'active'::text
    END
  ) STORED,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),

  CONSTRAINT url_route_source_system_shape_check CHECK (
    source_system IS NULL OR (
      length(source_system) BETWEEN 1 AND 64
      AND source_system = btrim(source_system)
    )
  ),
  CONSTRAINT url_route_source_type_shape_check CHECK (
    source_type IS NULL OR (
      length(source_type) BETWEEN 1 AND 64
      AND source_type = btrim(source_type)
    )
  ),
  CONSTRAINT url_route_source_id_shape_check CHECK (
    source_id IS NULL OR (
      length(source_id) BETWEEN 1 AND 255
      AND source_id = btrim(source_id)
    )
  ),
  CONSTRAINT url_route_static_key_shape_check CHECK (
    static_route_key IS NULL OR (
      length(static_route_key) BETWEEN 1 AND 128
      AND static_route_key = btrim(static_route_key)
    )
  ),
  CONSTRAINT url_route_equivalence_shape_check CHECK (
    equivalence_key IS NULL OR (
      length(equivalence_key) BETWEEN 1 AND 255
      AND equivalence_key = btrim(equivalence_key)
    )
  ),
  CONSTRAINT url_route_target_identity_check CHECK (
    (
      target_type = 'entity'
      AND source_system IS NOT NULL
      AND source_type IS NOT NULL
      AND source_id IS NOT NULL
      AND static_route_key IS NULL
    )
    OR
    (
      target_type = 'static'
      AND source_system IS NULL
      AND source_type IS NULL
      AND source_id IS NULL
      AND static_route_key IS NOT NULL
    )
  ),
  CONSTRAINT url_route_target_kind_check CHECK (
    (
      target_type = 'entity'
      AND kind IN (
        'product',
        'category',
        'brand',
        'collection',
        'campaign',
        'article',
        'page'
      )
    )
    OR (target_type = 'static' AND kind = 'static')
  ),
  CONSTRAINT url_route_successor_state_check CHECK (
    (
      status = 'superseded'
      AND successor_route_id IS NOT NULL
      AND successor_route_id <> id
    )
    OR
    (
      status <> 'superseded'
      AND successor_route_id IS NULL
    )
  ),
  CONSTRAINT url_route_source_identity_unique
    UNIQUE (market, source_system, source_type, source_id),
  CONSTRAINT url_route_static_identity_unique
    UNIQUE (market, static_route_key),
  CONSTRAINT url_route_scope_status_unique
    UNIQUE (id, market, kind, status),
  CONSTRAINT url_route_scope_target_unique
    UNIQUE (id, market, kind, target_type),
  CONSTRAINT url_route_successor_foreign
    FOREIGN KEY (successor_route_id, market, kind, successor_required_status)
    REFERENCES url_registry.url_route (id, market, kind, status)
    DEFERRABLE INITIALLY DEFERRED
);

CREATE UNIQUE INDEX url_route_active_equivalence_unique
  ON url_registry.url_route (market, kind, equivalence_key)
  WHERE status = 'active' AND equivalence_key IS NOT NULL;

CREATE INDEX url_route_successor_lookup_idx
  ON url_registry.url_route (successor_route_id)
  WHERE successor_route_id IS NOT NULL;

CREATE INDEX url_route_active_equivalence_lookup_idx
  ON url_registry.url_route (kind, equivalence_key, market)
  WHERE status = 'active' AND equivalence_key IS NOT NULL;

CREATE TABLE url_registry.url_entity_slug (
  id uuid PRIMARY KEY,
  market text NOT NULL CHECK (market IN ('sk', 'cz', 'hu', 'ro')),
  kind text NOT NULL CHECK (
    kind IN (
      'product',
      'category',
      'brand',
      'collection',
      'campaign',
      'article',
      'page'
    )
  ),
  normalized_slug text NOT NULL CHECK (
    length(normalized_slug) BETWEEN 1 AND 80
    AND normalized_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  ),
  route_id uuid,
  disposition text NOT NULL CHECK (disposition IN ('current', 'alias', 'gone')),
  required_route_target_type text GENERATED ALWAYS AS (
    CASE
      WHEN route_id IS NULL THEN NULL
      ELSE 'entity'::text
    END
  ) STORED,
  normalization_version integer NOT NULL CHECK (normalization_version > 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),

  CONSTRAINT url_entity_slug_route_state_check CHECK (
    (disposition IN ('current', 'alias') AND route_id IS NOT NULL)
    OR disposition = 'gone'
  ),
  CONSTRAINT url_entity_slug_market_kind_slug_unique
    UNIQUE (market, kind, normalized_slug),
  CONSTRAINT url_entity_slug_route_foreign
    FOREIGN KEY (route_id, market, kind, required_route_target_type)
    REFERENCES url_registry.url_route (id, market, kind, target_type)
    DEFERRABLE INITIALLY DEFERRED
);

CREATE UNIQUE INDEX url_entity_slug_one_current_per_route
  ON url_registry.url_entity_slug (route_id)
  WHERE disposition = 'current';

CREATE INDEX url_entity_slug_route_history_idx
  ON url_registry.url_entity_slug (route_id, disposition, created_at);

CREATE TABLE url_registry.static_route_path (
  id uuid PRIMARY KEY,
  market text NOT NULL CHECK (market IN ('sk', 'cz', 'hu', 'ro')),
  route_key text NOT NULL CHECK (
    length(route_key) BETWEEN 1 AND 128
    AND route_key = btrim(route_key)
  ),
  parent_route_key text CHECK (
    parent_route_key IS NULL OR (
      length(parent_route_key) BETWEEN 1 AND 128
      AND parent_route_key = btrim(parent_route_key)
    )
  ),
  segment text NOT NULL CHECK (
    length(segment) BETWEEN 1 AND 80
    AND segment ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  ),
  match_mode text NOT NULL CHECK (match_mode IN ('exact', 'prefix')),
  disposition text NOT NULL CHECK (disposition IN ('current', 'alias')),
  introduced_in_version integer NOT NULL CHECK (introduced_in_version > 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),

  CONSTRAINT static_route_path_parent_not_self_check CHECK (
    parent_route_key IS NULL OR parent_route_key <> route_key
  ),
  CONSTRAINT static_route_path_route_foreign
    FOREIGN KEY (market, route_key)
    REFERENCES url_registry.url_route (market, static_route_key)
    DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT static_route_path_parent_foreign
    FOREIGN KEY (market, parent_route_key)
    REFERENCES url_registry.url_route (market, static_route_key)
    DEFERRABLE INITIALLY DEFERRED
);

CREATE UNIQUE INDEX static_route_path_one_current_per_route
  ON url_registry.static_route_path (market, route_key)
  WHERE disposition = 'current';

-- NULL parent keys represent the root. COALESCE makes root paths participate in
-- uniqueness, so a historical path can never be reclaimed after localization.
CREATE UNIQUE INDEX static_route_path_no_reuse_unique
  ON url_registry.static_route_path (
    market,
    COALESCE(parent_route_key, ''),
    segment
  );

CREATE INDEX static_route_path_taxonomy_idx
  ON url_registry.static_route_path (
    market,
    parent_route_key,
    disposition,
    route_key
  );

CREATE TABLE url_registry.url_registry_command (
  idempotency_key text PRIMARY KEY CHECK (
    length(idempotency_key) BETWEEN 1 AND 255
    AND idempotency_key = btrim(idempotency_key)
  ),
  producer text NOT NULL CHECK (
    length(producer) BETWEEN 1 AND 64
    AND producer = btrim(producer)
  ),
  command_version integer NOT NULL CHECK (command_version > 0),
  command_type text NOT NULL CHECK (
    length(command_type) BETWEEN 1 AND 64
    AND command_type = btrim(command_type)
  ),
  request_fingerprint text NOT NULL CHECK (
    request_fingerprint ~ '^sha256:[0-9a-f]{64}$'
  ),
  source_system text NOT NULL CHECK (
    length(source_system) BETWEEN 1 AND 64
    AND source_system = btrim(source_system)
  ),
  source_type text NOT NULL CHECK (
    length(source_type) BETWEEN 1 AND 64
    AND source_type = btrim(source_type)
  ),
  source_id text NOT NULL CHECK (
    length(source_id) BETWEEN 1 AND 255
    AND source_id = btrim(source_id)
  ),
  source_version text NOT NULL CHECK (
    length(source_version) BETWEEN 1 AND 255
    AND source_version = btrim(source_version)
  ),
  source_event_id text NOT NULL CHECK (
    length(source_event_id) BETWEEN 1 AND 255
    AND source_event_id = btrim(source_event_id)
  ),
  expected_route_version integer NOT NULL CHECK (expected_route_version >= 0),
  status text NOT NULL DEFAULT 'in_progress' CHECK (
    status IN ('in_progress', 'completed')
  ),
  outcome text CHECK (outcome IN ('applied', 'noop')),
  route_id uuid,
  result_route_version integer CHECK (result_route_version > 0),
  response_snapshot jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  completed_at timestamptz,

  CONSTRAINT url_registry_command_result_pair_check CHECK (
    (route_id IS NULL AND result_route_version IS NULL)
    OR (route_id IS NOT NULL AND result_route_version IS NOT NULL)
  ),
  CONSTRAINT url_registry_command_completion_check CHECK (
    (
      status = 'in_progress'
      AND outcome IS NULL
      AND route_id IS NULL
      AND result_route_version IS NULL
      AND response_snapshot IS NULL
      AND completed_at IS NULL
    )
    OR
    (
      status = 'completed'
      AND outcome IS NOT NULL
      AND response_snapshot IS NOT NULL
      AND jsonb_typeof(response_snapshot) = 'object'
      AND completed_at IS NOT NULL
    )
  ),
  CONSTRAINT url_registry_command_route_foreign
    FOREIGN KEY (route_id)
    REFERENCES url_registry.url_route (id)
    DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT url_registry_command_source_event_unique
    UNIQUE (source_system, source_event_id)
);

-- One upstream event must fan out with distinct child event IDs when it creates
-- multiple market commands. This prevents a producer from applying an event
-- under a different idempotency key.
CREATE INDEX url_registry_command_route_idx
  ON url_registry.url_registry_command (route_id, created_at)
  WHERE route_id IS NOT NULL;

CREATE TABLE url_registry.url_registry_audit (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  command_idempotency_key text NOT NULL,
  route_id uuid,
  route_version integer CHECK (route_version > 0),
  event_type text NOT NULL CHECK (
    length(event_type) BETWEEN 1 AND 64
    AND event_type = btrim(event_type)
  ),
  before_state jsonb,
  after_state jsonb NOT NULL CHECK (jsonb_typeof(after_state) = 'object'),
  event_payload jsonb NOT NULL CHECK (jsonb_typeof(event_payload) = 'object'),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),

  CONSTRAINT url_registry_audit_route_version_pair_check CHECK (
    (route_id IS NULL AND route_version IS NULL)
    OR (route_id IS NOT NULL AND route_version IS NOT NULL)
  ),
  CONSTRAINT url_registry_audit_one_per_command_unique
    UNIQUE (command_idempotency_key),
  CONSTRAINT url_registry_audit_id_command_unique
    UNIQUE (id, command_idempotency_key),
  CONSTRAINT url_registry_audit_command_foreign
    FOREIGN KEY (command_idempotency_key)
    REFERENCES url_registry.url_registry_command (idempotency_key)
    DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT url_registry_audit_route_foreign
    FOREIGN KEY (route_id)
    REFERENCES url_registry.url_route (id)
    DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX url_registry_audit_route_version_idx
  ON url_registry.url_registry_audit (route_id, route_version, id)
  WHERE route_id IS NOT NULL;

CREATE TABLE url_registry.url_registry_invalidation_outbox (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  command_idempotency_key text NOT NULL,
  audit_id bigint NOT NULL,
  route_id uuid,
  route_version integer CHECK (route_version > 0),
  deduplication_key text NOT NULL UNIQUE CHECK (
    length(deduplication_key) BETWEEN 1 AND 255
    AND deduplication_key = btrim(deduplication_key)
  ),
  invalidation_tags text[] NOT NULL CHECK (
    cardinality(invalidation_tags) BETWEEN 1 AND 128
    AND array_position(invalidation_tags, NULL) IS NULL
    AND array_position(invalidation_tags, '') IS NULL
  ),
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  status text NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'processing', 'delivered', 'failed')
  ),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  available_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  locked_at timestamptz,
  locked_by text,
  delivered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),

  CONSTRAINT url_registry_outbox_route_version_pair_check CHECK (
    (route_id IS NULL AND route_version IS NULL)
    OR (route_id IS NOT NULL AND route_version IS NOT NULL)
  ),
  CONSTRAINT url_registry_outbox_one_per_command_unique
    UNIQUE (command_idempotency_key),
  CONSTRAINT url_registry_outbox_delivery_state_check CHECK (
    (
      status = 'pending'
      AND locked_at IS NULL
      AND locked_by IS NULL
      AND delivered_at IS NULL
    )
    OR
    (
      status = 'processing'
      AND locked_at IS NOT NULL
      AND locked_by IS NOT NULL
      AND delivered_at IS NULL
    )
    OR
    (
      status = 'delivered'
      AND locked_at IS NULL
      AND locked_by IS NULL
      AND delivered_at IS NOT NULL
    )
    OR
    (
      status = 'failed'
      AND locked_at IS NULL
      AND locked_by IS NULL
      AND delivered_at IS NULL
    )
  ),
  CONSTRAINT url_registry_outbox_audit_foreign
    FOREIGN KEY (audit_id, command_idempotency_key)
    REFERENCES url_registry.url_registry_audit (id, command_idempotency_key)
    DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT url_registry_outbox_route_foreign
    FOREIGN KEY (route_id)
    REFERENCES url_registry.url_route (id)
    DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX url_registry_invalidation_outbox_dispatch_idx
  ON url_registry.url_registry_invalidation_outbox (status, available_at, id)
  WHERE status IN ('pending', 'processing');

CREATE INDEX url_registry_invalidation_outbox_processing_reclaim_idx
  ON url_registry.url_registry_invalidation_outbox (locked_at, id)
  WHERE status = 'processing';

CREATE INDEX url_registry_invalidation_outbox_command_idx
  ON url_registry.url_registry_invalidation_outbox (
    command_idempotency_key,
    id
  );

CREATE FUNCTION url_registry.guard_url_route_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'URL route history cannot be deleted'
      USING ERRCODE = '23514';
  END IF;

  IF ROW(
    NEW.id,
    NEW.market,
    NEW.kind,
    NEW.target_type,
    NEW.source_system,
    NEW.source_type,
    NEW.source_id,
    NEW.static_route_key,
    NEW.created_at
  ) IS DISTINCT FROM ROW(
    OLD.id,
    OLD.market,
    OLD.kind,
    OLD.target_type,
    OLD.source_system,
    OLD.source_type,
    OLD.source_id,
    OLD.static_route_key,
    OLD.created_at
  ) THEN
    RAISE EXCEPTION 'URL route source and static identity are immutable'
      USING ERRCODE = '23514';
  END IF;

  IF NOT (
    NEW.status = OLD.status
    OR (OLD.status = 'active' AND NEW.status IN ('retired', 'superseded'))
    OR (OLD.status = 'superseded' AND NEW.status = 'retired')
  ) THEN
    RAISE EXCEPTION 'Invalid URL route lifecycle transition: % to %',
      OLD.status,
      NEW.status
      USING ERRCODE = '23514';
  END IF;

  IF NEW.version <> OLD.version + 1 THEN
    RAISE EXCEPTION 'URL route update must increment version by exactly one'
      USING ERRCODE = '23514';
  END IF;

  NEW.updated_at := clock_timestamp();
  RETURN NEW;
END;
$$;

CREATE TRIGGER url_route_mutation_guard
BEFORE UPDATE OR DELETE ON url_registry.url_route
FOR EACH ROW EXECUTE FUNCTION url_registry.guard_url_route_mutation();

CREATE FUNCTION url_registry.guard_entity_slug_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'URL entity slug history cannot be deleted'
      USING ERRCODE = '23514';
  END IF;

  IF NOT (
    OLD.disposition = 'current'
    AND NEW.disposition = 'alias'
    AND ROW(
      NEW.id,
      NEW.market,
      NEW.kind,
      NEW.normalized_slug,
      NEW.route_id,
      NEW.normalization_version,
      NEW.created_at
    ) IS NOT DISTINCT FROM ROW(
      OLD.id,
      OLD.market,
      OLD.kind,
      OLD.normalized_slug,
      OLD.route_id,
      OLD.normalization_version,
      OLD.created_at
    )
  ) THEN
    RAISE EXCEPTION 'Only a current URL entity slug may be demoted to an immutable alias'
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER url_entity_slug_history_guard
BEFORE UPDATE OR DELETE ON url_registry.url_entity_slug
FOR EACH ROW EXECUTE FUNCTION url_registry.guard_entity_slug_history();

CREATE FUNCTION url_registry.guard_static_path_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Static route path history cannot be deleted'
      USING ERRCODE = '23514';
  END IF;

  IF NOT (
    OLD.disposition = 'current'
    AND NEW.disposition = 'alias'
    AND ROW(
      NEW.id,
      NEW.market,
      NEW.route_key,
      NEW.parent_route_key,
      NEW.segment,
      NEW.match_mode,
      NEW.introduced_in_version,
      NEW.created_at
    ) IS NOT DISTINCT FROM ROW(
      OLD.id,
      OLD.market,
      OLD.route_key,
      OLD.parent_route_key,
      OLD.segment,
      OLD.match_mode,
      OLD.introduced_in_version,
      OLD.created_at
    )
  ) THEN
    RAISE EXCEPTION 'Only a current static path may be demoted to an immutable alias'
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER static_route_path_history_guard
BEFORE UPDATE OR DELETE ON url_registry.static_route_path
FOR EACH ROW EXECUTE FUNCTION url_registry.guard_static_path_history();

-- This deferred constraint performs one route PK lookup and one indexed
-- current-projection count for the affected route. It never scans every slug or
-- static path. The S3 20k Postgres gate must still measure its write overhead.
CREATE FUNCTION url_registry.assert_route_projection()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  affected_route_id uuid;
  affected_market text;
  affected_route_key text;
  affected_target_type text;
  affected_route_version integer;
  current_projection_count bigint;
  current_projection_version integer;
BEGIN
  IF TG_TABLE_NAME = 'url_route' THEN
    affected_route_id := NEW.id;
  ELSIF TG_TABLE_NAME = 'url_entity_slug' THEN
    affected_route_id := NEW.route_id;
  ELSIF TG_TABLE_NAME = 'static_route_path' THEN
    affected_market := NEW.market;
    affected_route_key := NEW.route_key;

    SELECT id
    INTO affected_route_id
    FROM url_registry.url_route
    WHERE market = affected_market
      AND static_route_key = affected_route_key;
  END IF;

  IF affected_route_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT target_type, market, static_route_key, version
  INTO
    affected_target_type,
    affected_market,
    affected_route_key,
    affected_route_version
  FROM url_registry.url_route
  WHERE id = affected_route_id;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  IF affected_target_type = 'entity' THEN
    SELECT count(*)
    INTO current_projection_count
    FROM url_registry.url_entity_slug
    WHERE route_id = affected_route_id
      AND disposition = 'current';

    IF current_projection_count <> 1 THEN
      RAISE EXCEPTION 'Entity URL route % must have exactly one current entity slug',
        affected_route_id
        USING ERRCODE = '23514';
    END IF;
  ELSE
    SELECT count(*), max(introduced_in_version)
    INTO current_projection_count, current_projection_version
    FROM url_registry.static_route_path
    WHERE market = affected_market
      AND route_key = affected_route_key
      AND disposition = 'current';

    IF current_projection_count <> 1 THEN
      RAISE EXCEPTION 'Static URL route % must have exactly one current static path',
        affected_route_id
        USING ERRCODE = '23514';
    END IF;

    IF current_projection_version > affected_route_version THEN
      RAISE EXCEPTION 'Current static path version cannot exceed route version'
        USING ERRCODE = '23514';
    END IF;
  END IF;

  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER url_route_projection_check
AFTER INSERT OR UPDATE ON url_registry.url_route
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION url_registry.assert_route_projection();

CREATE CONSTRAINT TRIGGER url_entity_slug_projection_check
AFTER INSERT OR UPDATE ON url_registry.url_entity_slug
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION url_registry.assert_route_projection();

CREATE CONSTRAINT TRIGGER static_route_path_projection_check
AFTER INSERT OR UPDATE ON url_registry.static_route_path
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION url_registry.assert_route_projection();

-- The recursive check follows only the current parent chain for the affected
-- logical route. Partial-current and taxonomy indexes bound each ancestor hop.
-- Static graph writes require one transaction-scoped per-market advisory lock.
-- Without that command/driver serialization, two
-- concurrent transactions could each close one half of a cycle while neither
-- snapshot sees the other's uncommitted edge. The deferred trigger validates
-- the final state after the per-market lock has serialized writers.
CREATE FUNCTION url_registry.assert_static_path_graph()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  affected_market text := NEW.market;
  affected_route_key text := NEW.route_key;
BEGIN
  IF EXISTS (
    WITH RECURSIVE ancestors (route_key, parent_route_key) AS (
      SELECT route_key, parent_route_key
      FROM url_registry.static_route_path
      WHERE market = affected_market
        AND route_key = affected_route_key
        AND disposition = 'current'

      UNION

      SELECT parent.route_key, parent.parent_route_key
      FROM url_registry.static_route_path AS parent
      INNER JOIN ancestors AS child
        ON parent.market = affected_market
        AND parent.route_key = child.parent_route_key
        AND parent.disposition = 'current'
    )
    SELECT 1
    FROM ancestors
    WHERE parent_route_key = affected_route_key
  ) THEN
    RAISE EXCEPTION 'Static route hierarchy cycle detected for %.%',
      affected_market,
      affected_route_key
      USING ERRCODE = '23514';
  END IF;

  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER static_route_path_graph_check
AFTER INSERT OR UPDATE ON url_registry.static_route_path
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION url_registry.assert_static_path_graph();

CREATE FUNCTION url_registry.guard_command_ledger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'URL registry command cannot be deleted'
      USING ERRCODE = '23514';
  END IF;

  IF NOT (
    OLD.status = 'in_progress'
    AND NEW.status = 'completed'
    AND ROW(
      NEW.idempotency_key,
      NEW.producer,
      NEW.command_version,
      NEW.command_type,
      NEW.request_fingerprint,
      NEW.source_system,
      NEW.source_type,
      NEW.source_id,
      NEW.source_version,
      NEW.source_event_id,
      NEW.expected_route_version,
      NEW.created_at
    ) IS NOT DISTINCT FROM ROW(
      OLD.idempotency_key,
      OLD.producer,
      OLD.command_version,
      OLD.command_type,
      OLD.request_fingerprint,
      OLD.source_system,
      OLD.source_type,
      OLD.source_id,
      OLD.source_version,
      OLD.source_event_id,
      OLD.expected_route_version,
      OLD.created_at
    )
  ) THEN
    RAISE EXCEPTION 'URL registry command permits only one in-progress to completed transition'
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER url_registry_command_guard
BEFORE UPDATE OR DELETE ON url_registry.url_registry_command
FOR EACH ROW EXECUTE FUNCTION url_registry.guard_command_ledger();

-- An in-progress row serializes a concurrent idempotency-key/source-event race,
-- but it may never become externally visible: the command, audit, and required
-- invalidation intent must all finish in the same transaction.
CREATE FUNCTION url_registry.assert_command_completed()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  persisted_status text;
  persisted_outcome text;
  persisted_audit_count bigint;
  persisted_outbox_count bigint;
BEGIN
  SELECT status, outcome
  INTO persisted_status, persisted_outcome
  FROM url_registry.url_registry_command
  WHERE idempotency_key = NEW.idempotency_key;

  IF persisted_status <> 'completed' THEN
    RAISE EXCEPTION 'URL registry command must complete in its write transaction'
      USING ERRCODE = '23514';
  END IF;

  SELECT count(*)
  INTO persisted_audit_count
  FROM url_registry.url_registry_audit
  WHERE command_idempotency_key = NEW.idempotency_key;

  IF persisted_audit_count <> 1 THEN
    RAISE EXCEPTION 'Completed URL registry command requires exactly one audit record'
      USING ERRCODE = '23514';
  END IF;

  SELECT count(*)
  INTO persisted_outbox_count
  FROM url_registry.url_registry_invalidation_outbox
  WHERE command_idempotency_key = NEW.idempotency_key;

  IF persisted_outcome = 'applied' AND persisted_outbox_count <> 1 THEN
    RAISE EXCEPTION 'Applied URL registry command requires exactly one invalidation outbox record'
      USING ERRCODE = '23514';
  END IF;

  IF persisted_outcome = 'noop' AND persisted_outbox_count <> 0 THEN
    RAISE EXCEPTION 'No-op URL registry command cannot emit invalidation outbox state'
      USING ERRCODE = '23514';
  END IF;

  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER url_registry_command_completed_deferred
AFTER INSERT OR UPDATE ON url_registry.url_registry_command
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION url_registry.assert_command_completed();

CREATE FUNCTION url_registry.deny_append_only_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION '%', TG_ARGV[0]
    USING ERRCODE = '23514';
END;
$$;

CREATE TRIGGER url_registry_audit_append_only
BEFORE UPDATE OR DELETE ON url_registry.url_registry_audit
FOR EACH ROW EXECUTE FUNCTION url_registry.deny_append_only_mutation(
  'URL registry audit is append-only'
);

CREATE FUNCTION url_registry.guard_invalidation_outbox()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'URL registry invalidation outbox cannot be deleted'
      USING ERRCODE = '23514';
  END IF;

  IF ROW(
    NEW.id,
    NEW.command_idempotency_key,
    NEW.audit_id,
    NEW.route_id,
    NEW.route_version,
    NEW.deduplication_key,
    NEW.invalidation_tags,
    NEW.payload,
    NEW.created_at
  ) IS DISTINCT FROM ROW(
    OLD.id,
    OLD.command_idempotency_key,
    OLD.audit_id,
    OLD.route_id,
    OLD.route_version,
    OLD.deduplication_key,
    OLD.invalidation_tags,
    OLD.payload,
    OLD.created_at
  ) THEN
    RAISE EXCEPTION 'URL registry invalidation payload is immutable'
      USING ERRCODE = '23514';
  END IF;

  IF NEW.attempt_count < OLD.attempt_count THEN
    RAISE EXCEPTION 'URL registry invalidation attempt count cannot decrease'
      USING ERRCODE = '23514';
  END IF;

  IF NOT (
    NEW.status = OLD.status
    OR (OLD.status = 'pending' AND NEW.status = 'processing')
    OR (
      OLD.status = 'processing'
      AND NEW.status IN ('pending', 'delivered', 'failed')
    )
    OR (OLD.status = 'failed' AND NEW.status = 'pending')
  ) THEN
    RAISE EXCEPTION 'Invalid URL registry invalidation outbox transition: % to %',
      OLD.status,
      NEW.status
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER url_registry_invalidation_outbox_guard
BEFORE UPDATE OR DELETE ON url_registry.url_registry_invalidation_outbox
FOR EACH ROW EXECUTE FUNCTION url_registry.guard_invalidation_outbox();
