/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'article-categories': ArticleCategory;
    articles: Article;
    'page-categories': PageCategory;
    pages: Page;
    'hero-carousels': HeroCarousel;
    'translation-exclusions': TranslationExclusion;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'article-categories': ArticleCategoriesSelect<false> | ArticleCategoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'page-categories': PageCategoriesSelect<false> | PageCategoriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'hero-carousels': HeroCarouselsSelect<false> | HeroCarouselsSelect<true>;
    'translation-exclusions': TranslationExclusionsSelect<false> | TranslationExclusionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('cs' | 'en' | 'sk' | 'pl' | 'hu' | 'ro' | 'sl')
    | ('cs' | 'en' | 'sk' | 'pl' | 'hu' | 'ro' | 'sl')[];
  globals: {
    'translation-settings': TranslationSetting;
  };
  globalsSelect: {
    'translation-settings': TranslationSettingsSelect<false> | TranslationSettingsSelect<true>;
  };
  locale: 'cs' | 'en' | 'sk' | 'pl' | 'hu' | 'ro' | 'sl';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories".
 */
export interface ArticleCategory {
  id: number;
  title: string;
  /**
   * URL-friendly version of the title (e.g., "health")
   */
  slug: string;
  /**
   * When enabled, changes in the default language will automatically translate to other languages
   */
  translationSync?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL friendly version of the title (e.g., 'my-article')
   */
  slug: string;
  /**
   * Short summary shown in the articles list
   */
  excerpt: string;
  /**
   * Main article content with rich text editor + table support
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  contentHTML?: string | null;
  /**
   * Image shown as the article preview
   */
  featuredImage: number | Media;
  category: number | ArticleCategory;
  /**
   * Tags for better search and categorization
   */
  tags?: string[] | null;
  author?: (number | null) | User;
  publishedDate: string;
  status: 'draft' | 'published' | 'archived';
  /**
   * Estimated reading time in minutes
   */
  readingTime?: number | null;
  analytics?: {
    views?: number | null;
    shares?: number | null;
    lastViewed?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, changes in the default language will automatically translate to other languages
   */
  translationSync?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-categories".
 */
export interface PageCategory {
  id: number;
  title: string;
  /**
   * URL-friendly version of the title (e.g., "support")
   */
  slug: string;
  /**
   * When enabled, changes in the default language will automatically translate to other languages
   */
  translationSync?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-friendly version of the title (e.g., "about-us")
   */
  slug: string;
  category?: (number | null) | PageCategory;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentHTML?: string | null;
  visibility: 'public' | 'customers-only';
  status: 'draft' | 'published' | 'archived';
  publishedDate: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, changes in the default language will automatically translate to other languages
   */
  translationSync?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-carousels".
 */
export interface HeroCarousel {
  id: number;
  image: number | Media;
  heading: string;
  subheading?: string | null;
  button?: string | null;
  buttonHref?: string | null;
  /**
   * When enabled, changes in the default language will automatically translate to other languages
   */
  translationSync?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stores field-level translation exclusions per document and locale. Each locale can have its own set of excluded fields. There should only be ONE record per (collectionSlug, documentId, locale) combination.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translation-exclusions".
 */
export interface TranslationExclusion {
  id: number;
  /**
   * The collection this exclusion belongs to
   */
  collectionSlug: string;
  /**
   * The ID of the document
   */
  documentId: string;
  /**
   * The locale these exclusions apply to (e.g., "en", "de", "fr")
   */
  locale: string;
  /**
   * Fields that should NOT be auto-translated in this specific locale. Each locale has its own independent set of exclusions.
   */
  excludedPaths: {
    /**
     * Field path (e.g., "title", "content.0.description")
     */
    path: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'article-categories';
        value: number | ArticleCategory;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'page-categories';
        value: number | PageCategory;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'hero-carousels';
        value: number | HeroCarousel;
      } | null)
    | ({
        relationTo: 'translation-exclusions';
        value: number | TranslationExclusion;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories_select".
 */
export interface ArticleCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  translationSync?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  contentHTML?: T;
  featuredImage?: T;
  category?: T;
  tags?: T;
  author?: T;
  publishedDate?: T;
  status?: T;
  readingTime?: T;
  analytics?:
    | T
    | {
        views?: T;
        shares?: T;
        lastViewed?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  translationSync?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-categories_select".
 */
export interface PageCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  translationSync?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  content?: T;
  contentHTML?: T;
  visibility?: T;
  status?: T;
  publishedDate?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  translationSync?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-carousels_select".
 */
export interface HeroCarouselsSelect<T extends boolean = true> {
  image?: T;
  heading?: T;
  subheading?: T;
  button?: T;
  buttonHref?: T;
  translationSync?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translation-exclusions_select".
 */
export interface TranslationExclusionsSelect<T extends boolean = true> {
  collectionSlug?: T;
  documentId?: T;
  locale?: T;
  excludedPaths?:
    | T
    | {
        path?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure translation settings including the system prompt and model parameters
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translation-settings".
 */
export interface TranslationSetting {
  id: number;
  lockTranslationSettings?: boolean | null;
  /**
   * The main instruction for the AI translator. Use {fromLocale} and {toLocale} as placeholders.
   */
  systemPrompt: string;
  /**
   * ⚠️ Do not edit if you don't know what you are doing. These rules ensure proper JSON translation behavior.
   */
  translationRules: string;
  /**
   * The OpenAI model to use for translations (e.g., gpt-4o, gpt-4o-mini)
   */
  model: string;
  /**
   * Controls randomness in translation (0.0-2.0). Lower values are more deterministic.
   */
  temperature: number;
  /**
   * Maximum tokens for the response. Leave empty for automatic.
   */
  maxTokens?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translation-settings_select".
 */
export interface TranslationSettingsSelect<T extends boolean = true> {
  lockTranslationSettings?: T;
  systemPrompt?: T;
  translationRules?: T;
  model?: T;
  temperature?: T;
  maxTokens?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}