const spacingScale = Array.from({ length: 19 }, (_, index) =>
  String((index + 1) * 50),
)

export default {
  scanDirectories: ["src/app", "src/components"],
  fileExtensions: [".ts", ".tsx"],
  exclude: [
    "**/*.stories.tsx",
    "**/*.test.tsx",
    "**/*.spec.tsx",
    "src/app/theme/**",
    "src/components/storefront-data-smoke-panel.tsx",
    "src/components/storefront-query-monitor-panel.tsx",
    "src/components/storefront-query-monitor-bridge.tsx",
  ],
  rules: {
    noArbitraryValues: {
      enabled: true,
      allowClassPatterns: [
        /^icon-\[[^\]]+\]$/,
        /^token-icon-[\w-]+$/,
        /^\[scrollbar-width:none\]$/,
        /^\[&::-webkit-scrollbar\]:hidden$/,
      ],
    },
    noTailwindPalette: {
      enabled: true,
      colorUtilityPrefixes: [
        "bg",
        "text",
        "border",
        "fill",
        "stroke",
        "ring",
        "ring-offset",
        "outline",
        "shadow",
        "accent",
        "caret",
        "decoration",
        "from",
        "via",
        "to",
      ],
      paletteNames: [
        "black",
        "white",
        "slate",
        "gray",
        "zinc",
        "neutral",
        "stone",
        "red",
        "orange",
        "amber",
        "yellow",
        "lime",
        "green",
        "emerald",
        "teal",
        "cyan",
        "sky",
        "blue",
        "indigo",
        "violet",
        "purple",
        "fuchsia",
        "pink",
        "rose",
      ],
    },
    noTailwindSpacingScale: {
      enabled: true,
      prefixes: [
        "p",
        "px",
        "py",
        "pt",
        "pr",
        "pb",
        "pl",
        "m",
        "mx",
        "my",
        "mt",
        "mr",
        "mb",
        "ml",
        "gap",
        "gap-x",
        "gap-y",
        "space-x",
        "space-y",
        "w",
        "h",
        "min-w",
        "max-w",
        "min-h",
        "max-h",
        "top",
        "right",
        "bottom",
        "left",
        "inset",
        "inset-x",
        "inset-y",
      ],
      allowedNumericValues: ["0", ...spacingScale],
      allowedKeywords: [
        "px",
        "auto",
        "full",
        "screen",
        "min",
        "max",
        "fit",
        "svh",
        "lvh",
        "dvh",
      ],
    },
    noTailwindContainerScale: {
      enabled: true,
      prefixes: ["w", "min-w", "max-w", "h", "min-h", "max-h"],
      disallowedValues: [
        "xs",
        "sm",
        "md",
        "lg",
        "xl",
        "2xl",
        "3xl",
        "4xl",
        "5xl",
        "6xl",
        "7xl",
        "screen-sm",
        "screen-md",
        "screen-lg",
        "screen-xl",
        "screen-2xl",
      ],
    },
  },
}
